(()=>{
'use strict';
const API='/api/fhm-clip-demo';
const STORE='fhmClipCapturesV3';
const SEEDS={'GOAL|42:03|16|Барчук Г.':'2026-09-10T08:08:00Z'};
const captures=new Map(Object.entries(JSON.parse(localStorage.getItem(STORE)||'{}')));
let data=null,player=null,lastVideoTime=NaN,known=new Set(),inClip=false,clipTimer=null,currentClip=null,flashQueue=[],flashBusy=false,newKeys=new Set();
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shortKey=e=>[e.type,e.time,e.number,e.player].join('|');
const save=()=>localStorage.setItem(STORE,JSON.stringify(Object.fromEntries(captures)));
function teamName(side){return side==='away'?data?.teams?.away?.name:data?.teams?.home?.name}
function logoHtml(t){return t?.logo?`<img src="${esc(t.logo)}" alt="">`:'<div class="ph">U16</div>'}
function setPlayerState(text,cls=''){const e=$('#playerState');e.textContent=text;e.className='pstate '+cls}
function current(){try{const n=Number(player?.getCurrentTime?.());if(Number.isFinite(n)){lastVideoTime=n;return n}}catch{}return lastVideoTime}
function fmtVideo(n){if(!Number.isFinite(Number(n)))return'—';n=Math.max(0,Math.floor(Number(n)));return`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`}
function titleFor(e){return({GOAL:'Гол',PENALTY:'Удаление',MATCH_START:'Начало матча',MATCH_END:'Матч завершён',TIMEOUT:'Тайм-аут',GOALIE:'Вратарь'})[e.type]||e.rawName||'Событие'}
function detailsFor(e){if(e.type==='GOAL'){const a=[e.assist1,e.assist2].filter(Boolean);return a.length?`Передачи: ${a.join(', ')}`:'Без результативных передач'}if(e.type==='PENALTY')return`${e.penaltyMinutes?e.penaltyMinutes+' мин. · ':''}${e.violation||'Нарушение правил'}`;if(e.type==='MATCH_START')return'Матч начался';if(e.type==='MATCH_END')return'Финальная сирена';if(e.type==='TIMEOUT')return`${teamName(e.side)||'Команда'} берёт тайм-аут`;return e.player||e.rawName||''}
function iconFor(e){if(e.type==='MATCH_START')return'▶';if(e.type==='MATCH_END')return'■';if(e.type==='TIMEOUT')return'T';if(e.type==='GOALIE')return'ВР';return'•'}
function renderScore(pop=false){if(!data)return;$('#matchTitle').textContent=data.title||'Матч';$('#matchPhase').textContent=data.status==='FINAL'?'Завершён':'LIVE · '+data.currentPeriod+' период';$('#mainScore').textContent=`${data.score?.home??0}:${data.score?.away??0}`;$('#periodLabel').textContent=data.status==='FINAL'?'Матч завершён':`${data.currentPeriod} период`;$('#homeTeam').innerHTML=`${logoHtml(data.teams?.home)}<strong>${esc(data.teams?.home?.name||'Команда 1')}</strong>`;$('#awayTeam').innerHTML=`${logoHtml(data.teams?.away)}<strong>${esc(data.teams?.away?.name||'Команда 2')}</strong>`;$('#periodScores').innerHTML=[1,2,3].map(n=>{const p=(data.periodScores||[]).find(x=>x.period===n)||{home:0,away:0};return`<div class="pc ${n===data.currentPeriod&&data.status!=='FINAL'?'active':''}"><span>${n} период</span><strong>${p.home}:${p.away}</strong></div>`}).join('');if(pop){const box=$('#scoreBox');box.classList.remove('pop');void box.offsetWidth;box.classList.add('pop')}}
function eventCard(e){const isVideo=e.type==='GOAL'||e.type==='PENALTY',cap=captures.get(e.key),active=!!(cap&&Number.isFinite(Number(cap.start))),cls=e.type==='GOAL'?'goal':e.type==='PENALTY'?'pen':'system';return`<article class="event ${cls} ${newKeys.has(e.key)?'new':''}"><div class="etime"><strong>${esc(e.time||'—')}</strong><small>${e.period?e.period+' период':''}</small></div><div class="emain"><span class="etype">${esc(titleFor(e))}${e.type==='GOAL'?` <span class="escore">${esc(e.score)}</span>`:''}</span><strong>${e.number?`№${esc(e.number)} `:''}${esc(e.player||teamName(e.side)||titleFor(e))}</strong><p>${esc(detailsFor(e))}${active?' · <span style="color:#81ddb5">видео готово</span>':''}</p></div>${isVideo?`<button class="play ${active?'':'wait'}" type="button" data-key="${esc(e.key)}" ${active?'':'disabled'} aria-label="${active?'Смотреть видео':'Видео ещё синхронизируется'}"></button>`:`<div class="eicon">${esc(iconFor(e))}</div>`}</article>`}
function renderFeed(){if(!data)return;const events=data.events||[];let html='';for(let p=3;p>=1;p--){const xs=events.filter(e=>(e.period||1)===p&&!(p>1&&e.type==='MATCH_START')).reverse();if(!xs.length&&p>data.currentPeriod)continue;html+=`<div class="divider"><span>${p} период</span></div>`;html+=xs.map(eventCard).join('')}$('#feed').innerHTML=html||'<div class="info">Событий пока нет.</div>'}
function render(pop=false){renderScore(pop);renderFeed()}
function queueFlash(e){flashQueue.push(e);runFlash()}
function runFlash(){if(flashBusy||!flashQueue.length)return;flashBusy=true;const e=flashQueue.shift(),f=$('#flash');f.className='flash '+(e.type==='GOAL'?'goal':e.type==='PENALTY'?'pen':'period');if(e.type==='GOAL'){$('#flashKicker').textContent=teamName(e.side)||'Гол';$('#flashTitle').textContent='ГОООЛ!';$('#flashMain').textContent=(e.number?`№${e.number} `:'')+(e.player||'');$('#flashSub').textContent=e.time+' · '+e.period+' период';$('#flashScore').textContent=e.score||''}else if(e.type==='PENALTY'){$('#flashKicker').textContent=teamName(e.side)||'Удаление';$('#flashTitle').textContent='УДАЛЕНИЕ';$('#flashMain').textContent=(e.number?`№${e.number} `:'')+(e.player||'');$('#flashSub').textContent=(e.penaltyMinutes?e.penaltyMinutes+' мин. · ':'')+(e.violation||'Нарушение');$('#flashScore').textContent=e.time||''}else{$('#flashKicker').textContent='Матч продолжается';$('#flashTitle').textContent=`${e.period} ПЕРИОД`;$('#flashMain').textContent='Команды возвращаются на лёд';$('#flashSub').textContent='LIVE';$('#flashScore').textContent=''}requestAnimationFrame(()=>f.classList.add('show'));setTimeout(()=>{f.classList.remove('show');setTimeout(()=>{flashBusy=false;runFlash()},280)},2800)}
function storeWindow(e,start,end,source='live'){if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)return;captures.set(e.key,{start:Math.max(0,start),end:Math.max(0,end),source,capturedAt:new Date().toISOString()});save()}
function captureNew(e){const t=current();if(!Number.isFinite(t)||captures.has(e.key))return;if(e.type==='GOAL')storeWindow(e,t-65,t-5,'live-detection');else if(e.type==='PENALTY')storeWindow(e,t-55,t-4,'live-detection')}
function restoreSeeded(){if(!data)return;const t=current();if(!Number.isFinite(t))return;for(const e of data.events||[]){if(captures.has(e.key))continue;const wall=SEEDS[shortKey(e)];if(!wall)continue;const eventVideo=t-(Date.now()-Date.parse(wall))/1000;if(eventVideo>0)storeWindow(e,eventVideo-26,eventVideo+28,'seeded')}renderFeed()}
function goLive(){if(!player)return;clearInterval(clipTimer);inClip=false;currentClip=null;try{player.seekLive?.();player.mute?.();player.play?.()}catch{}$('#clipBar').classList.remove('show');setPlayerState('LIVE · синхронизация','sync')}
function seek(sec){try{player?.seek?.(Math.max(0,Number(sec)||0));player?.play?.()}catch{}}
function playClip(key){const cap=captures.get(key);if(!cap||!player)return;const e=(data.events||[]).find(x=>x.key===key);currentClip={key,...cap};inClip=true;clearInterval(clipTimer);seek(cap.start);try{player.unmute?.()}catch{}$('#clipText').textContent=`${titleFor(e)} · ${e?.time||''} · ${e?.player||''}`;$('#clipBar').classList.add('show');setPlayerState(`Видео момента · ${fmtVideo(cap.start)}–${fmtVideo(cap.end)}`,'ok');clipTimer=setInterval(()=>{const t=current();if(Number.isFinite(t)&&t>=Number(cap.end))goLive()},300)}
function nudge(delta){const t=current();if(Number.isFinite(t))seek(t+delta)}
async function poll(first=false){try{const r=await fetch(`${API}?_=${Date.now()}`,{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error||'Ошибка протокола');const prevScore=data?`${data.score?.home}:${data.score?.away}`:null,prevPeriod=data?.currentPeriod||1;data=b;const keys=new Set((b.events||[]).map(e=>e.key));if(first){known=keys}else{const added=(b.events||[]).filter(e=>!known.has(e.key));for(const e of added){newKeys.add(e.key);if(e.type==='GOAL'||e.type==='PENALTY'){captureNew(e);queueFlash(e)}}if((b.currentPeriod||1)>prevPeriod)queueFlash({type:'PERIOD',period:b.currentPeriod});known=keys;setTimeout(()=>{newKeys.clear();renderFeed()},5000)}render(prevScore&&prevScore!==`${b.score?.home}:${b.score?.away}`);$('#watchStatus').textContent=b.status==='FINAL'?'Матч завершён':'LIVE';$('#updated').textContent='обновлено '+new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'});if(first)restoreSeeded()}catch(e){$('#watchStatus').textContent='Ошибка';setPlayerState(String(e),'err')}}
function initPlayer(){if(!data)return;const frame=$('#vkPlayer');frame.src=data.video.embed+'&autoplay=1';const hook=()=>{try{if(!window.VK?.VideoPlayer)return setTimeout(hook,250);player=VK.VideoPlayer(frame);player.on?.('inited',()=>{setPlayerState('VK подключён · LIVE','sync');setTimeout(()=>{goLive();restoreSeeded()},450)});player.on?.('timeupdate',s=>{const n=Number(s?.time??s);if(Number.isFinite(n))lastVideoTime=n;if(!inClip&&Number.isFinite(n))setPlayerState(`LIVE · ${fmtVideo(n)}`,'sync')});player.on?.('error',()=>setPlayerState('Ошибка VK-плеера','err'));setTimeout(()=>restoreSeeded(),1800)}catch{setTimeout(hook,450)}};hook()}
$('#feed').addEventListener('click',e=>{const b=e.target.closest('.play[data-key]:not(.wait)');if(b)playClip(b.dataset.key)});$('#backLive').addEventListener('click',goLive);$('#clipBack').addEventListener('click',()=>nudge(-10));$('#clipForward').addEventListener('click',()=>nudge(10));
(async()=>{await poll(true);initPlayer();setInterval(()=>poll(false),2000)})();
})();
