(()=>{
'use strict';
const API='/api/fhm-clip-demo';
const STORE='fhmClipCapturesV7_game17349';
const SHOWN='fhmShownAnimationsV2_game17349';
const captures=new Map(Object.entries(JSON.parse(localStorage.getItem(STORE)||'{}')));
const shown=new Set(JSON.parse(localStorage.getItem(SHOWN)||'[]'));
let data=null,player=null,lastVideoTime=NaN,known=new Set(),inClip=false,clipTimer=null,newKeys=new Set(),lastFeedSig='',animationBusy=false,pendingFeed=false,animQueue=[];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const saveCaptures=()=>localStorage.setItem(STORE,JSON.stringify(Object.fromEntries(captures)));
const saveShown=()=>localStorage.setItem(SHOWN,JSON.stringify([...shown]));
function installLiveEventCss(){if(document.getElementById('clip-live-event-css'))return;const s=document.createElement('style');s.id='clip-live-event-css';s.textContent=`
.timeline>.event{grid-template-columns:58px 46px minmax(0,1fr) auto!important}.timeline>.event.system{grid-template-columns:58px minmax(0,1fr)!important}.timeline>.event.system .event-team-logo{display:none!important}.event-team-logo{width:42px!important;height:42px!important;object-fit:contain;align-self:center}.event-person{display:flex;align-items:center;gap:10px;min-width:0}.event-player-photo{width:46px;height:46px;flex:0 0 46px;border-radius:50%;object-fit:cover;background:#11263e;border:1px solid rgba(255,255,255,.1)}.event-person-copy{min-width:0}.event-person-copy strong{display:block}.event-team-name{display:block;margin-top:4px;color:#c1d2e2;font-size:9px;font-weight:850}
@media(max-width:580px){.timeline>.event{grid-template-columns:50px 38px minmax(0,1fr) 36px!important;gap:8px!important}.timeline>.event.system{grid-template-columns:50px minmax(0,1fr)!important}.event-team-logo{width:34px!important;height:34px!important}.event-player-photo{width:40px;height:40px;flex-basis:40px}.event-person{gap:8px}.event-person-copy strong{font-size:11px!important}}
`;document.head.appendChild(s)}
function team(side){if(side==='home')return data?.teams?.home;if(side==='away')return data?.teams?.away;return null}
function teamName(side){return team(side)?.name||''}
function teamLogo(side){return team(side)?.logo||''}
function colorTeamName(name=''){return String(name).replace(/\s+20\d{2}\s*$/,'').trim()}
function logoHtml(t){return t?.logo?`<img src="${esc(t.logo)}" alt="">`:'<div class="ph">U16</div>'}
function setPlayerState(text,cls=''){const e=$('#playerState');if(!e)return;e.textContent=text;e.className='pstate '+cls}
function current(){try{const n=Number(player?.getCurrentTime?.());if(Number.isFinite(n)){lastVideoTime=n;return n}}catch{}return lastVideoTime}
function fmtVideo(n){if(!Number.isFinite(Number(n)))return'—';n=Math.max(0,Math.floor(Number(n)));return`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`}
function effectiveStatus(){if(!data)return'LIVE';const startMs=Date.parse(data.start||'');if(Number.isFinite(startMs)){if(Date.now()<startMs)return'SCHEDULED';const age=Date.now()-startMs;if(data.status==='FINAL'&&!(data.events||[]).some(e=>e.type==='MATCH_END')&&age<2.5*60*60*1000)return'LIVE'}return data.status||'LIVE'}
function titleFor(e){return({GOAL:'Гол',PENALTY:'Удаление',MATCH_START:'Начало матча',MATCH_END:'Матч завершён',PERIOD_START:'Начало периода',PERIOD_END:'Конец периода',TIMEOUT:'Тайм-аут',GOALIE:'Смена вратаря'})[e.type]||e.rawName||'Событие'}
function detailsFor(e){if(e.type==='GOAL'){const a=[e.assist1,e.assist2].filter(Boolean);return a.length?`Передачи: ${a.join(', ')}`:'Без результативных передач'}if(e.type==='PENALTY')return`${e.penaltyMinutes?e.penaltyMinutes+' мин. · ':''}${e.violation||'Нарушение правил'}`;if(e.type==='MATCH_START')return'Матч начался';if(e.type==='MATCH_END')return'Финальная сирена';if(e.type==='PERIOD_START')return`${e.period} период начался`;if(e.type==='PERIOD_END')return`${e.period} период завершён`;if(e.type==='TIMEOUT')return`${teamName(e.side)||'Команда'} берёт тайм-аут`;return e.player||e.rawName||''}
function renderScore(pop=false){if(!data)return;const st=effectiveStatus();$('#matchTitle').textContent=data.title||'Матч';$('#matchPhase').textContent=st==='FINAL'?'Завершён':st==='SCHEDULED'?'Скоро':'LIVE · '+data.currentPeriod+' период';$('#mainScore').textContent=`${data.score?.home??0}:${data.score?.away??0}`;$('#periodLabel').textContent=st==='FINAL'?'Матч завершён':st==='SCHEDULED'?'До начала':`${data.currentPeriod} период`;$('#homeTeam').innerHTML=`${logoHtml(data.teams?.home)}<strong>${esc(data.teams?.home?.name||'Команда 1')}</strong>`;$('#awayTeam').innerHTML=`${logoHtml(data.teams?.away)}<strong>${esc(data.teams?.away?.name||'Команда 2')}</strong>`;$('#periodScores').innerHTML=[1,2,3].map(n=>{const p=(data.periodScores||[]).find(x=>x.period===n)||{home:0,away:0};return`<div class="pc ${n===data.currentPeriod&&st==='LIVE'?'active':''}"><span>${n} период</span><strong>${p.home}:${p.away}</strong></div>`}).join('');if(pop){const box=$('#scoreBox');box.classList.remove('pop');void box.offsetWidth;box.classList.add('pop')}}
function systemCard(type,period,time,text){return`<article class="event system"><div class="etime"><strong>${esc(time)}</strong><small>${period?period+' период':''}</small></div><div class="emain"><span class="etype">${esc(titleFor({type,period}))}</span><strong>${esc(text)}</strong><p>${esc(detailsFor({type,period}))}</p></div></article>`}
function eventCard(e){if(e.type==='MATCH_START')return systemCard('MATCH_START',1,e.time||'00:00','Начало матча');const isVideo=e.type==='GOAL'||e.type==='PENALTY',cap=captures.get(e.key),active=!!(cap&&Number.isFinite(Number(cap.start))),cls=e.type==='GOAL'?'goal':e.type==='PENALTY'?'penalty':'system',logo=teamLogo(e.side),name=teamName(e.side),colorName=colorTeamName(name),teamPenalty=e.type==='PENALTY'&&(e.isTeamPenalty||!String(e.player||'').trim()),main=teamPenalty?'Командный штраф':`${e.number?`№${e.number} `:''}${e.player||name||titleFor(e)}`,photo=!teamPenalty?String(e.photo||''):'';return`<article class="event ${cls} ${newKeys.has(e.key)?'new':''}" data-event-key="${esc(e.key)}" data-event-type="${esc(e.type)}" data-team-name="${esc(colorName)}" data-team-logo="${esc(logo)}" data-penalty-minutes="${esc(e.penaltyMinutes||2)}" data-penalty-reason="${esc(e.violation||'Нарушение правил')}"><div class="etime"><strong>${esc(e.time||'—')}</strong><small>${e.period?e.period+' период':''}</small></div>${logo?`<img class="event-team-logo" src="${esc(logo)}" alt="${esc(name)}">`:''}<div class="emain"><div class="event-person">${photo?`<img class="event-player-photo" src="${esc(photo)}" alt="${esc(e.player||'Игрок')}">`:''}<div class="event-person-copy"><span class="etype">${esc(titleFor(e))}${e.type==='GOAL'?` <span class="escore">${esc(e.score)}</span>`:''}</span><strong>${esc(main)}</strong>${name?`<span class="event-team-name">${esc(name)}</span>`:''}<p>${esc(detailsFor(e))}${active?' · <span style="color:#81ddb5">видео готово</span>':''}</p></div></div></div>${isVideo?`<button class="play ${active?'':'wait'}" type="button" data-key="${esc(e.key)}" ${active?'':'disabled'} aria-label="${active?'Смотреть видео':'Видео ещё синхронизируется'}"></button>`:''}</article>`}
function renderFeed(){if(!data)return;const st=effectiveStatus(),events=(data.events||[]).filter(e=>!(st==='SCHEDULED'&&e.type==='MATCH_START'));if(st==='SCHEDULED'){$('#feed').innerHTML='<div class="info">Матч ещё не начался. Протокол подключён.</div>';return}let html='';for(let p=3;p>=1;p--){const xs=events.filter(e=>(e.period||1)===p&&e.type!=='MATCH_START').reverse();if(!xs.length&&p>data.currentPeriod&&st!=='FINAL')continue;html+=`<div class="divider"><span>${p} период</span></div>`;const completed=st==='FINAL'||p<data.currentPeriod;if(st==='FINAL'&&p===3)html+=systemCard('MATCH_END',3,'60:00','Матч завершён');if(completed)html+=systemCard('PERIOD_END',p,p===1?'20:00':p===2?'40:00':'60:00',`Конец ${p} периода`);html+=xs.map(eventCard).join('');if(p>1&&(st==='FINAL'||p<=data.currentPeriod))html+=systemCard('PERIOD_START',p,p===2?'20:00':'40:00',`Начало ${p} периода`)}const start=events.find(e=>e.type==='MATCH_START');if(start)html+=`<div class="divider"><span>Старт матча</span></div>${eventCard(start)}`;$('#feed').innerHTML=html||'<div class="info">LIVE-протокол подключён. Ждём первое событие.</div>'}
function feedSignature(){return[(data?.events||[]).map(e=>[e.key,e.photo||'',e.player||'',e.number||'',e.penaltyMinutes||0,e.violation||'',e.score||''].join('|')).join('||'),data?.currentPeriod,effectiveStatus()].join('::')}
function cardFor(e){return[...document.querySelectorAll('[data-event-key]')].find(el=>el.dataset.eventKey===e.key)||null}
function playNextAnimation(){if(animationBusy||!animQueue.length)return;const e=animQueue.shift();if(shown.has(e.key)){playNextAnimation();return}let card=cardFor(e);if(!card){renderFeed();card=cardFor(e)}if(!card){shown.add(e.key);saveShown();playNextAnimation();return}animationBusy=true;const fn=e.type==='GOAL'?window.CupMHLAnimations?.goal:window.CupMHLAnimations?.penalty;const ok=fn?.(card)!==false;if(!ok){animationBusy=false;setTimeout(playNextAnimation,250);return}const wait=e.type==='GOAL'?5250:6050;setTimeout(()=>{shown.add(e.key);saveShown();animationBusy=false;if(pendingFeed){renderFeed();pendingFeed=false;lastFeedSig=feedSignature()}playNextAnimation()},wait)}
function queueAnimation(e){if(!e||shown.has(e.key)||animQueue.some(x=>x.key===e.key))return;animQueue.push(e);playNextAnimation()}
function storeWindow(e,start,end,source='live'){if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)return;captures.set(e.key,{start:Math.max(0,start),end:Math.max(0,end),source,capturedAt:new Date().toISOString()});saveCaptures()}
function captureNew(e){const t=current();if(!Number.isFinite(t)||captures.has(e.key))return;if(e.type==='GOAL')storeWindow(e,t-40,t+15,'live-detection');else if(e.type==='PENALTY')storeWindow(e,t-30,t+12,'live-detection')}
function goLive(){if(!player)return;clearInterval(clipTimer);inClip=false;try{player.seekLive?.();player.mute?.();player.play?.()}catch{}$('#clipBar').classList.remove('show');setPlayerState('LIVE · синхронизация','sync')}
function seek(sec){try{player?.seek?.(Math.max(0,Number(sec)||0));player?.play?.()}catch{}}
function playClip(key){const cap=captures.get(key);if(!cap||!player)return;const e=(data.events||[]).find(x=>x.key===key),label=e?.type==='PENALTY'&&(e?.isTeamPenalty||!e?.player)?'Командный штраф':e?.player||'';inClip=true;clearInterval(clipTimer);seek(cap.start);try{player.unmute?.()}catch{}$('#clipText').textContent=`${titleFor(e)} · ${e?.time||''} · ${label}`;$('#clipBar').classList.add('show');setPlayerState(`Видео момента · ${fmtVideo(cap.start)}–${fmtVideo(cap.end)}`,'ok');clipTimer=setInterval(()=>{const t=current();if(Number.isFinite(t)&&t>=Number(cap.end))goLive()},300)}
function nudge(delta){const t=current();if(Number.isFinite(t))seek(t+delta)}
async function poll(first=false){try{const r=await fetch(`${API}?_=${Date.now()}`,{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error||'Ошибка протокола');const prevScore=data?`${data.score?.home}:${data.score?.away}`:null,oldKnown=known;data=b;const keys=new Set((b.events||[]).map(e=>e.key)),added=first?[]:(b.events||[]).filter(e=>!oldKnown.has(e.key));for(const e of added){newKeys.add(e.key);if(e.type==='GOAL'||e.type==='PENALTY')captureNew(e)}known=keys;renderScore(prevScore&&prevScore!==`${b.score?.home}:${b.score?.away}`);const sig=feedSignature();if(sig!==lastFeedSig){if(animationBusy)pendingFeed=true;else{renderFeed();lastFeedSig=sig}}const st=effectiveStatus();$('#watchStatus').textContent=st==='FINAL'?'Матч завершён':st==='SCHEDULED'?'Ожидаем старт':'LIVE';$('#updated').textContent='обновлено '+new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'});if(first){const unseen=(b.events||[]).filter(e=>(e.type==='GOAL'||e.type==='PENALTY')&&!shown.has(e.key));if(unseen.length){const e=unseen[unseen.length-1];captureNew(e);queueAnimation(e)}}else added.filter(e=>e.type==='GOAL'||e.type==='PENALTY').forEach(queueAnimation);if(added.length)setTimeout(()=>{newKeys.clear();if(!animationBusy)renderFeed()},7000)}catch(e){$('#watchStatus').textContent='Ошибка';setPlayerState(String(e),'err')}}
function initPlayer(){if(!data)return;const frame=$('#vkPlayer');frame.src=data.video.embed+(String(data.video.embed||'').includes('autoplay=')?'':'&autoplay=1');const hook=()=>{try{if(!window.VK?.VideoPlayer)return setTimeout(hook,250);player=VK.VideoPlayer(frame);player.on?.('inited',()=>{setPlayerState('VK подключён · LIVE','sync');setTimeout(goLive,450)});player.on?.('timeupdate',s=>{const n=Number(s?.time??s);if(Number.isFinite(n))lastVideoTime=n;if(!inClip&&Number.isFinite(n))setPlayerState(`LIVE · ${fmtVideo(n)}`,'sync')});player.on?.('error',()=>setPlayerState('Ошибка VK-плеера','err'))}catch{setTimeout(hook,450)}};hook()}
installLiveEventCss();$('#feed').addEventListener('click',e=>{const play=e.target.closest('.play[data-key]:not(.wait)');if(play){e.preventDefault();e.stopPropagation();playClip(play.dataset.key);return}const card=e.target.closest('.event[data-event-key]');if(!card)return;const ev=(data?.events||[]).find(x=>x.key===card.dataset.eventKey);if(ev&&(ev.type==='GOAL'||ev.type==='PENALTY')){shown.delete(ev.key);saveShown();queueAnimation(ev)}});$('#backLive').addEventListener('click',goLive);$('#clipBack').addEventListener('click',()=>nudge(-10));$('#clipForward').addEventListener('click',()=>nudge(10));(async()=>{await poll(true);initPlayer();setInterval(()=>poll(false),2000)})();
})();
