(()=>{
'use strict';
const B=window.RussianCupTeamBranding;if(!B)return;
const grid=document.getElementById('goalGrid');if(!grid)return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const scoreFor=i=>`${(i%4)+1}:${i%3}`;
function cardHtml(team,i){const ink=B.inkFor(team.color);return `<article class="goal-card" tabindex="0" role="button" aria-label="Проиграть голевую анимацию ${esc(team.name)}" data-team="${esc(team.name)}" style="--team-color:${team.color};--team-ink:${ink}"><div class="etime"><strong>${String(7+(i%13)).padStart(2,'0')}:${String((i*7)%60).padStart(2,'0')}</strong><span>${(i%3)+1} период</span></div><img class="team-logo" src="${team.logo}" alt="Логотип ${esc(team.name)}"><div class="event-copy"><span class="event-label">Гол</span><strong>Тестовый гол</strong><small>${esc(team.name)}</small><p>Проверка фирменного цвета и логотипа</p></div><div class="score">${scoreFor(i)}</div><div class="brand-row"><div class="color-meta"><span class="swatch"></span><code>${team.color}</code></div><span class="tap-note">Нажми, чтобы проиграть</span></div></article>`}
grid.innerHTML=B.teams.map(cardHtml).join('');
for(const t of B.teams){const im=new Image();im.src=t.logo}
const states=new WeakMap();
function contentNodes(card){return [...card.children].filter(el=>!el.classList.contains('goal-stage'))}
function stop(card){const st=states.get(card);if(st){st.animations.forEach(a=>{try{a.cancel()}catch{}});clearTimeout(st.timer);st.nodes.forEach(({el,opacity})=>{if(el.isConnected)el.style.opacity=opacity})}states.delete(card);card.querySelector('.goal-stage')?.remove()}
function play(card){if(!card||!card.isConnected)return;stop(card);const team=B.get(card.dataset.team);if(!team)return;card.style.setProperty('--team-color',team.color);card.style.setProperty('--team-ink',B.inkFor(team.color));const stage=document.createElement('div');stage.className='goal-stage';stage.innerHTML=`<div class="goal-word left">ГООООООООЛ!</div><div class="goal-stage-logo"><img src="${team.logo}" alt=""></div><div class="goal-word right">ГООООООООЛ!</div>`;card.appendChild(stage);const nodes=contentNodes(card).filter(el=>el!==stage).map(el=>({el,opacity:el.style.opacity}));nodes.forEach(({el})=>el.style.opacity='0');const duration=5000;const stageAnim=stage.animate([{clipPath:'inset(0 0 100% 0)',offset:0},{clipPath:'inset(0 0 100% 0)',offset:.06},{clipPath:'inset(0 0 0 0)',offset:.22},{clipPath:'inset(0 0 0 0)',offset:.64},{clipPath:'inset(0 0 100% 0)',offset:1}],{duration,easing:'cubic-bezier(.65,0,.35,1)',fill:'both'});const nodeAnimations=nodes.map(({el})=>el.animate([{opacity:0,offset:0},{opacity:0,offset:.64},{opacity:1,offset:.70},{opacity:1,offset:1}],{duration,easing:'linear',fill:'both'}));const drop=card.animate([{transform:'translateY(-16px)',opacity:.35},{transform:'translateY(0)',opacity:1}],{duration:340,easing:'cubic-bezier(.18,.8,.25,1)'});const animations=[stageAnim,...nodeAnimations,drop];const timer=setTimeout(()=>stop(card),duration+100);states.set(card,{animations,timer,nodes})}
let lastTouchAt=0,touchStart=null;
grid.addEventListener('touchstart',e=>{if(e.touches.length!==1){touchStart=null;return}const t=e.touches[0],card=e.target.closest('.goal-card');touchStart=card?{card,x:t.clientX,y:t.clientY}:null},{passive:true});
grid.addEventListener('touchend',e=>{if(!touchStart||!e.changedTouches.length)return;const t=e.changedTouches[0],start=touchStart;touchStart=null;if(Math.hypot(t.clientX-start.x,t.clientY-start.y)>22)return;e.preventDefault();lastTouchAt=performance.now();play(start.card)},{passive:false});
grid.addEventListener('touchcancel',()=>{touchStart=null},{passive:true});
grid.addEventListener('click',e=>{if(performance.now()-lastTouchAt<500)return;const card=e.target.closest('.goal-card');if(card)play(card)});
grid.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const card=e.target.closest('.goal-card');if(!card)return;e.preventDefault();play(card)});
})();
