(()=>{
'use strict';
const EDGE='https://wcucbtdfkghjirpbqzzk.supabase.co/functions/v1/russian-cup-match-center';
const LOGOS={
'Динамо Москва':'https://drive.google.com/thumbnail?id=1I3KuJZEajmksDKtoBsdj4h_75fU0e_KY&sz=w512','МАХ':'https://drive.google.com/thumbnail?id=1Veii4NYgKc06nRtxKmCRQv1YCE164YZP&sz=w512','Торпедо':'https://drive.google.com/thumbnail?id=17NYLCFaSrX6q4g0T7jhBnmidrI1JzKl9&sz=w512','Локомотив':'https://drive.google.com/thumbnail?id=1D6wJnaawN4kMt-1ZWTSvf-trYkslzyKi&sz=w512','Авангард':'https://drive.google.com/thumbnail?id=1y6CZfZSXYDVqCAjOvv6xB_7Fwu1AQwvn&sz=w512','Локомотив 2004':'https://drive.google.com/thumbnail?id=1sq7UHtBq_xiexekxmzWawF3yVTaEl-J-&sz=w512','Крылья Советов':'https://drive.google.com/thumbnail?id=1n6ViHZhkRvq_R_Ul1PEHnFnX7HVNk6-p&sz=w512','Сибирь':'https://drive.google.com/thumbnail?id=1Xul8VXC7juk2NHQfb28Cl9Jt_Kj0Obw-&sz=w512','Лада':'https://drive.google.com/thumbnail?id=15mcwMoXT7OaH46jj8w90PCeTtJY54UAF&sz=w512','Трактор':'https://drive.google.com/thumbnail?id=1qWTRWy-p36RDSMlAy4AqA60PrrUTaczd&sz=w512','Ак Барс':'https://drive.google.com/thumbnail?id=1I09r6XwD-9L4r5ojPGKCHsJ5WGUyOFy1&sz=w512','Спартак':'https://drive.google.com/thumbnail?id=19kJ3uz-yyb1Z2y8qvRbFwuw_2kjUUD2f&sz=w512','Динамо СПБ':'https://drive.google.com/thumbnail?id=1x4KaAFMJ_qfmi26oVjnsc-huKpWtqBbh&sz=w512','Динамо-Джуниверс':'https://drive.google.com/thumbnail?id=1HTqvh6fg5ZzOLFwOtY62zucjnRZyOXmu&sz=w512','СКА-Стрельна':'https://drive.google.com/thumbnail?id=1DH_sKpyVZsh6vnt8Q1_ovBpDuVkPHrNh&sz=w512','АКМ':'https://drive.google.com/thumbnail?id=1NmPj1OwI3C1yuNmgt2XX57HbEiiDauB7&sz=w512','ЦСКА':'https://drive.google.com/thumbnail?id=1bT6o4afTqonyA05keLbe_nfQ78sAmNda&sz=w512','Армия СКА':'https://drive.google.com/thumbnail?id=14XZX2FRyR5x_aVkU2SMLhW-Emk0RUkTo&sz=w512','Нефтехимик':'https://drive.google.com/thumbnail?id=1csEdtjesEvgAFSsfnfhmWUnUE23Tnqeg&sz=w512','Северсталь':'https://drive.google.com/thumbnail?id=10xBTOFy_ps1G3LNaHV3WpbQkuZ74pjRn&sz=w512','Красная Машина Юниор':'https://drive.google.com/thumbnail?id=1qATM0WxWDCgYfemDQvhdy30Ub0sWSWWV&sz=w512'};
let DATA=null,selectedLine=1,lastFetch=0,pollTimer=null;
const id=Number(new URL(location.href).searchParams.get('id'));
const $=s=>document.querySelector(s);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=x=>String(x||'').toLocaleLowerCase('ru-RU').replace(/[«»"']/g,'').replace(/ё/g,'е').replace(/\s+/g,' ').trim();
function logo(team){return team?.logo_url||LOGOS[team?.name]||''}
function scheduleTeam(side,g){const t=side==='home'?g.home_team:g.away_team;return{...t,logo_url:t?.logo_url||LOGOS[t?.name]||''}}
function fmtDate(d,opts={day:'numeric',month:'long',year:'numeric'}){try{return new Date(d+'T12:00:00').toLocaleDateString('ru-RU',opts)}catch{return d||''}}
function fmtDay(d){try{return new Date(d+'T12:00:00').toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'short'})}catch{return d}}
function startMs(m=DATA?.match){const t=String(m?.start_time||'').slice(0,5);return m?.game_date&&/^\d{2}:\d{2}$/.test(t)?Date.parse(`${m.game_date}T${t}:00+03:00`):NaN}
function state(){const m=DATA?.match,l=DATA?.live,db=String(m?.fhr_live_state||'').toUpperCase();if(l?.status==='FINAL'||m?.fhr_live_final_at||db==='FINAL')return'FINAL';const start=startMs();if(Number.isFinite(start)&&Date.now()<start)return'SCHEDULED';if(l?.status==='ACTIVE'||['WATCHING','ERROR'].includes(db))return'ACTIVE';return'SCHEDULED'}
function livePeriod(){if(state()==='FINAL')return'FINAL';const txt=String(DATA?.live?.status_text||'');if(/перерыв/i.test(txt))return'BREAK';return DATA?.live?.current_period||'1'}
function stateLabel(){const s=state(),p=livePeriod();if(s==='FINAL')return'Матч завершён';if(s==='SCHEDULED')return'Матч не начался';if(p==='BREAK')return'Перерыв · LIVE';if(p==='OT')return'● LIVE · Овертайм';if(p==='SO')return'● LIVE · Буллиты';return`● LIVE · ${p||'1'} период`}
function gameDone(g){return String(g.fhr_live_state||'').toUpperCase()==='FINAL'||Boolean(g.fhr_live_final_at)||(Number.isInteger(g.home_score)&&Number.isInteger(g.away_score)&&g.home_score!==g.away_score)}
function gameLive(g){if(gameDone(g))return false;const s=startMs(g);if(Number.isFinite(s)&&Date.now()<s)return false;return['WATCHING','ERROR'].includes(String(g.fhr_live_state||'').toUpperCase())}
function scheduleHtml(){const all=DATA.schedule||[],date=DATA.match.game_date,dates=[...new Set(all.map(x=>x.game_date))].sort(),idx=dates.indexOf(date),wanted=[date];if(idx>=0&&dates[idx+1])wanted.push(dates[idx+1]);const tabs=wanted.map((d,i)=>`<span class="day-tab ${i===0?'active':''}">${i===0?'Текущий игровой день':'Следующий игровой день'} · ${esc(fmtDay(d))}</span>`).join('');const games=all.filter(g=>wanted.includes(g.game_date)).map(g=>{const current=Number(g.id)===Number(DATA.match.id),done=gameDone(g),live=gameLive(g),hs=done||live?g.home_score:null,as=done||live?g.away_score:null,h=scheduleTeam('home',g),a=scheduleTeam('away',g),top=done||live?`${hs??0}:${as??0}`:(g.start_time||'—');const row=(t,v)=>`<div class="mini-team mini-team-logo"><span class="mini-team-name">${t.logo_url?`<img src="${esc(t.logo_url)}" alt="">`:''}<span>${esc(t.name)}</span></span>${v!==null?`<b>${v}</b>`:''}</div>`;return`<a class="mini-game ${current?'current':''}" href="/match.html?id=${g.id}"><div class="mini-top"><span>${esc(fmtDay(g.game_date))} · №${g.game_no??'—'}</span><span class="mini-score ${live?'live-dot':''}">${live?'● ':''}${esc(top)}</span></div><div class="mini-teams">${row(h,hs)}${row(a,as)}</div></a>`}).join('');return`<section class="dayrail wrap"><div class="dayrail-head"><strong>Матчи игрового дня</strong><span class="dayrail-note">Выберите матч, чтобы перейти в его LIVE-центр</span></div><div class="day-tabs">${tabs}</div><div class="game-strip">${games}</div></section>`}
function rawPeriods(){if(state()==='SCHEDULED')return[];const l=DATA.live||{},m=DATA.match||{};const fromLive=Array.isArray(l.period_scores)?l.period_scores:[];const fallback=[[m.p1_home,m.p1_away],[m.p2_home,m.p2_away],[m.p3_home,m.p3_away],[m.ot_home,m.ot_away],[m.so_home,m.so_away]];return [0,1,2,3,4].map(i=>Array.isArray(fromLive[i])&&fromLive[i].every(Number.isInteger)?fromLive[i]:(fallback[i].every(Number.isInteger)?fallback[i]:null))}
function periodHtml(){const ps=rawPeriods(),m=DATA.match||{},p=livePeriod(),showOT=Boolean(ps[3])||['OT','SO'].includes(String(m.finish_type||''))||p==='OT'||p==='SO',showSO=Boolean(ps[4])||String(m.finish_type||'')==='SO'||p==='SO';const defs=[['1-й период',0],['2-й период',1],['3-й период',2]];if(showOT)defs.push(['Овертайм',3]);if(showSO)defs.push(['Буллиты',4]);return defs.map(([label,i])=>`<div class="period-chip period-chip-main"><span>${label}</span><strong>${ps[i]?`${ps[i][0]}:${ps[i][1]}`:'— : —'}</strong></div>`).join('')}
function scoreboardHtml(){const m=DATA.match,h=DATA.home_team,a=DATA.away_team,hl=logo(h),al=logo(a),st=state(),place=[m.city,m.arena].filter(Boolean).join(' · ');return`<section class="score-section wrap"><article class="score-card"><div class="match-kicker">${esc(DATA.stage?.name||'')} · ${esc(DATA.group?.name||DATA.group?.code||'')} · Матч №${m.game_no??'—'}</div><div class="score-grid"><div class="score-team"><div class="score-logo">${hl?`<img src="${esc(hl)}" alt="Логотип ${esc(h.name)}">`:''}</div><h1>${esc(h.name)}</h1><p>${esc(h.city||'')}</p></div><div class="score-center"><div class="match-state ${st==='ACTIVE'?'live':''}">${esc(stateLabel())}</div><div class="live-track ${st==='ACTIVE'?'show':''}"></div><div class="period-line period-line-main">${periodHtml()}</div></div><div class="score-team"><div class="score-logo">${al?`<img src="${esc(al)}" alt="Логотип ${esc(a.name)}">`:''}</div><h1>${esc(a.name)}</h1><p>${esc(a.city||'')}</p></div></div><div class="score-meta"><span>${esc(fmtDate(m.game_date))} · ${esc(m.start_time||'Время уточняется')}</span><span>${esc(place||'Место проведения уточняется')}</span>${m.stream_url?`<a class="stream-btn" target="_blank" rel="noopener noreferrer" href="${esc(m.stream_url)}">▶ Смотреть трансляцию</a>`:''}<span id="freshness" class="freshness">Обновлено только что</span></div></article></section>`}
function lineup(side){return Array.isArray(DATA?.lineups?.[side])?DATA.lineups[side]:[]}
function teamBySide(side){return side==='away'?DATA.away_team:DATA.home_team}
function playerForEvent(ev){const list=lineup(ev.side==='away'?'away':'home'),n=Number(ev.number);let p=Number.isInteger(n)?list.find(x=>Number(x.number)===n):null;if(!p&&ev.player){const q=norm(ev.player);p=list.find(x=>norm(x.name)===q||norm(x.name).includes(q)||q.includes(norm(x.name)))||null}return p}
function photoHtml(ev){const p=playerForEvent(ev),src=p?.photo_proxy||p?.photo||'';return src?`<img class="event-photo" src="${esc(src)}" alt="${esc(p.name)}" loading="lazy">`:''}
function actualScore(ev){if(!Array.isArray(ev.score))return null;return DATA.live?.orientation==='reverse'?[ev.score[1],ev.score[0]]:ev.score}
function goalNarrative(ev){const s=actualScore(ev),team=teamBySide(ev.side)?.name||'Команда';if(!s)return`${team} забрасывает шайбу`;const [h,a]=s,total=h+a,sc=ev.side==='away'?a:h,opp=ev.side==='away'?h:a;if(total===1)return`${team} открывает счёт`;if(h===a)return`${team} сравнивает счёт`;if(sc===opp+1)return`${team} выходит вперёд`;if(sc>opp+1)return`${team} увеличивает преимущество`;if(sc<opp)return`${team} сокращает отставание`;return`${team} забрасывает шайбу`}
function onIceHtml(ev){if(!ev.on_ice)return'';const block=(side,title)=>{const xs=ev.on_ice?.[side]||[];return xs.length?`<div class="on-ice-team"><strong>${esc(title)}</strong><div class="ice-chips">${xs.map(p=>`<span class="ice-chip">№${p.number} ${esc(p.name)}</span>`).join('')}</div></div>`:''};return`<details class="on-ice"><summary>Кто был на льду в момент события</summary><div class="on-ice-grid">${block('home',DATA.home_team.name)}${block('away',DATA.away_team.name)}</div></details>`}
function eventFeedHtml(){const evs=Array.isArray(DATA.live?.events)&&DATA.live.events.length?DATA.live.events:[];if(!evs.length)return'<div class="empty">Событий матча пока нет. LIVE-протокол появится здесь автоматически после начала игры.</div>';return`<div class="timeline">${evs.map(ev=>{const type=String(ev.event_type||'').toUpperCase(),team=teamBySide(ev.side),l=logo(team),num=ev.number?`№${ev.number} `:'',period=ev.period==='OT'?'ОТ':ev.period==='SO'?'Буллиты':`${ev.period||'—'} период`,s=actualScore(ev);let cls='',label='Событие',title=ev.player||team?.name||'Матч',desc=ev.description||'';if(type==='GOAL'){cls='goal';label='Гол';title=`${num}${ev.player||''}`.trim()||team?.name;desc=goalNarrative(ev)+(ev.assistants?` · Передачи: ${ev.assistants}`:'')+(ev.power_play?' · В большинстве':'')}else if(type==='PENALTY'){cls='penalty';label='Удаление';title=`${num}${ev.player||'Командный штраф'}`.trim();desc=[ev.penalty_minutes?`${ev.penalty_minutes} мин.`:'',ev.description||''].filter(Boolean).join(' · ')}else if(type==='GOALKEEPER'){cls='goalkeeper';label=ev.empty_net?'Пустые ворота':'Вратарь';title=`${num}${ev.player||'Вратарь'}`.trim();desc=team?.name||''}else if(type==='TIMEOUT'){cls='goalkeeper';label='Тайм-аут';title=team?.name||'Команда';desc='Тайм-аут команды'}return`<article class="event-card ${cls}"><div class="event-time"><strong>${esc(ev.clock||'—')}</strong><span>${esc(period)}</span></div>${l?`<img class="event-logo" src="${esc(l)}" alt="">`:'<span></span>'}<div class="event-main">${photoHtml(ev)}<div class="event-copy"><span class="event-label">${esc(label)}</span><strong>${esc(title)}</strong><p>${esc(desc)}</p></div></div><div class="event-score">${s?`${s[0]}:${s[1]}`:''}</div>${type==='GOAL'?onIceHtml(ev):''}</article>`}).join('')}</div>`}
function rosterRows(list){return list.map(p=>`<div class="player-row"><span class="player-num">${p.number??'—'}</span><span class="player-avatar">${p.photo_proxy||p.photo?`<img src="${esc(p.photo_proxy||p.photo)}" alt="${esc(p.name)}" loading="lazy">`:(p.number??'')}</span><span class="player-name">${esc(p.name)}<small>${p.position==='G'?'Вратарь':p.position==='D'?'Защитник':p.position==='F'?'Нападающий':''}</small></span><span class="player-tag">${esc(p.goalie_role||p.captain||(p.line?`${p.line} зв.`:''))}</span></div>`).join('')}
function rosterTeamHtml(side){const team=teamBySide(side),list=lineup(side),l=logo(team);if(!list.length)return`<article class="roster-team"><div class="roster-head">${l?`<img src="${esc(l)}" alt="">`:''}<div><strong>${esc(team.name)}</strong><div class="roster-source">Состав на матч · ФХР</div></div></div><div class="empty">ФХР ещё не опубликовала заявку этой команды на конкретный матч.</div></article>`;const groups=[['G','Вратари'],['D','Защитники'],['F','Нападающие'],['U','Игроки']];return`<article class="roster-team"><div class="roster-head">${l?`<img src="${esc(l)}" alt="">`:''}<div><strong>${esc(team.name)}</strong><div class="roster-source">Состав на матч · ФХР</div></div></div>${groups.map(([pos,title])=>{const xs=list.filter(p=>(p.position||'U')===pos);return xs.length?`<div class="roster-group-title">${title}</div>${rosterRows(xs)}`:''}).join('')}</article>`}
function linePlayers(side,line){const list=lineup(side),d=list.filter(p=>p.position==='D'&&Number(p.line)===line).slice(0,2),f=list.filter(p=>p.position==='F'&&Number(p.line)===line).slice(0,3),g=list.find(p=>p.position==='G'&&p.goalie_role==='ОВ')||list.find(p=>p.position==='G');return{d,f,g}}
function availableLines(){return[1,2,3,4].filter(n=>lineup('home').some(p=>Number(p.line)===n)||lineup('away').some(p=>Number(p.line)===n))}
function rinkPlayer(p,cls,away=false){if(!p)return'';const src=p.photo_proxy||p.photo||'',surname=String(p.name||'').split(' ')[0];return`<div class="rink-player ${away?'away':''} ${cls}"><div class="rink-avatar">${src?`<img src="${esc(src)}" alt="${esc(p.name)}">`:''}<span class="rink-number">${p.number??'—'}</span></div><div class="rink-name">${esc(surname)}</div></div>`}
function rinkHtml(){const lines=availableLines();if(!lines.length)return'<div class="empty">Сочетания появятся после публикации официального состава на матч с номерами звеньев.</div>';if(!lines.includes(selectedLine))selectedLine=lines[0];const h=linePlayers('home',selectedLine),a=linePlayers('away',selectedLine),buttons=lines.map(n=>`<button class="line-tab ${n===selectedLine?'active':''}" type="button" data-line="${n}">${n}-е сочетание</button>`).join('');return`<div class="rink-shell"><div class="line-tabs">${buttons}</div><div class="rink"><span class="center-dot"></span><span class="faceoff f1"></span><span class="faceoff f2"></span><span class="faceoff f3"></span><span class="faceoff f4"></span>${rinkPlayer(h.d[0],'pos-hd1')}${rinkPlayer(h.d[1],'pos-hd2')}${rinkPlayer(h.f[0],'pos-hf1')}${rinkPlayer(h.f[1],'pos-hf2')}${rinkPlayer(h.f[2],'pos-hf3')}${rinkPlayer(a.d[0],'pos-ad1',true)}${rinkPlayer(a.d[1],'pos-ad2',true)}${rinkPlayer(a.f[0],'pos-af1',true)}${rinkPlayer(a.f[1],'pos-af2',true)}${rinkPlayer(a.f[2],'pos-af3',true)}</div><div class="goalies"><div class="goalie-card"><div><strong>${esc(DATA.home_team.name)}</strong>${h.g?`№${h.g.number} ${esc(h.g.name)}`:'Вратарь не указан'}</div></div><div class="goalie-card"><div><strong>${esc(DATA.away_team.name)}</strong>${a.g?`№${a.g.number} ${esc(a.g.name)}`:'Вратарь не указан'}</div></div></div><div class="rink-legend"><span>${esc(DATA.home_team.name)} · слева</span><span>${selectedLine}-е сочетание</span><span>${esc(DATA.away_team.name)} · справа</span></div></div>`}
function bodyHtml(){return`${scheduleHtml()}${scoreboardHtml()}<div class="sticky-tabs"><nav class="wrap section-tabs"><a href="#live">Ход матча</a><a href="#rosters">Составы</a><a href="#lines">Пятёрки на льду</a></nav></div><section class="section wrap" id="live"><div class="section-head"><div><div class="section-kicker">LIVE · протокол</div><h2 class="section-title">Ход матча</h2></div><div class="section-note">Голы, удаления, события с вратарями и другие ключевые эпизоды обновляются автоматически.</div></div>${eventFeedHtml()}</section><section class="section wrap" id="rosters"><div class="section-head"><div><div class="section-kicker">Заявка на игру</div><h2 class="section-title">Составы команд</h2></div><div class="section-note">Здесь показываются только игроки, заявленные ФХР непосредственно на этот матч. Общая карточка команды больше не используется как подмена.</div></div><div class="roster-grid">${rosterTeamHtml('home')}${rosterTeamHtml('away')}</div></section><section class="section wrap" id="lines"><div class="section-head"><div><div class="section-kicker">Тактика</div><h2 class="section-title">Пятёрки на хоккейной карте</h2></div><div class="section-note">Карта строится только по официальным сочетаниям конкретного матча.</div></div><div id="rinkRoot">${rinkHtml()}</div></section>`}
function injectStyle(){if(document.getElementById('mc-v2-style'))return;const s=document.createElement('style');s.id='mc-v2-style';s.textContent=`.mini-team-logo{align-items:center}.mini-team-name{display:flex;align-items:center;gap:7px;min-width:0}.mini-team-name img{width:22px;height:22px;object-fit:contain;flex:0 0 auto}.mini-team-name span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.period-line-main{margin-top:16px;gap:8px}.period-chip-main{min-width:88px;padding:10px 12px}.period-chip-main span{font-size:8px}.period-chip-main strong{font-size:18px;margin-top:5px}.score-center{min-width:240px}#rosters .section-head .section-note{display:none!important}#rosters .roster-head{position:relative;padding-right:175px;min-height:78px}#rosters .roster-head .roster-source{position:absolute;right:14px;top:14px;margin:0}@media(max-width:620px){#rosters .roster-head{padding-right:14px;padding-top:54px}#rosters .roster-head .roster-source{left:14px;right:auto;top:12px}}@media(max-width:820px){.score-center{min-width:0}.period-chip-main{min-width:68px;padding:8px}.period-chip-main strong{font-size:14px}}@media(max-width:520px){.period-line-main{margin-left:-30px;margin-right:-30px}.period-chip-main{min-width:64px}}`;document.head.appendChild(s)}
function bind(){document.querySelectorAll('[data-line]').forEach(b=>b.onclick=()=>{selectedLine=Number(b.dataset.line);const root=$('#rinkRoot');if(root){root.innerHTML=rinkHtml();bind()}})}
function freshness(){const el=$('#freshness');if(!el||!lastFetch)return;const sec=Math.floor((Date.now()-lastFetch)/1000);el.textContent=sec<5?'Обновлено только что':`Обновлено ${sec} сек. назад`}
async function load({quiet=false}={}){if(!Number.isInteger(id)||id<1){$('#main').innerHTML='<div class="wrap status-page">Матч не найден.</div>';return}try{const r=await fetch(`${EDGE}?match_id=${id}&_=${Date.now()}`,{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error||'Не удалось загрузить матч');DATA=b;lastFetch=Date.now();document.title=`${DATA.home_team.name} — ${DATA.away_team.name} · Матч-центр`;$('#main').innerHTML=bodyHtml();bind();freshness();schedule()}catch(e){if(!quiet||!DATA)$('#main').innerHTML=`<div class="wrap status-page">${esc(e.message||'Не удалось загрузить матч-центр.')}</div>`;schedule(true)}}
function schedule(error=false){clearTimeout(pollTimer);pollTimer=setTimeout(()=>load({quiet:true}),error?30000:state()==='ACTIVE'?15000:state()==='SCHEDULED'?30000:60000)}
injectStyle();setInterval(freshness,1000);load();
})();