(()=>{
'use strict';
const EDGE='https://wcucbtdfkghjirpbqzzk.supabase.co/functions/v1/russian-cup-match-center';
const ROSTER='https://wcucbtdfkghjirpbqzzk.supabase.co/functions/v1/russian-cup-fhr-roster';
const LOGOS={
'Динамо Москва':'https://drive.google.com/thumbnail?id=1I3KuJZEajmksDKtoBsdj4h_75fU0e_KY&sz=w512','МАХ':'https://drive.google.com/thumbnail?id=1Veii4NYgKc06nRtxKmCRQv1YCE164YZP&sz=w512','Торпедо':'https://drive.google.com/thumbnail?id=17NYLCFaSrX6q4g0T7jhBnmidrI1JzKl9&sz=w512','Локомотив':'https://drive.google.com/thumbnail?id=1D6wJnaawN4kMt-1ZWTSvf-trYkslzyKi&sz=w512','Авангард':'https://drive.google.com/thumbnail?id=1y6CZfZSXYDVqCAjOvv6xB_7Fwu1AQwvn&sz=w512','Локомотив 2004':'https://drive.google.com/thumbnail?id=1sq7UHtBq_xiexekxmzWawF3yVTaEl-J-&sz=w512','Крылья Советов':'https://drive.google.com/thumbnail?id=1n6ViHZhkRvq_R_Ul1PEHnFnX7HVNk6-p&sz=w512','Сибирь':'https://drive.google.com/thumbnail?id=1Xul8VXC7juk2NHQfb28Cl9Jt_Kj0Obw-&sz=w512','Лада':'https://drive.google.com/thumbnail?id=15mcwMoXT7OaH46jj8w90PCeTtJY54UAF&sz=w512','Трактор':'https://drive.google.com/thumbnail?id=1qWTRWy-p36RDSMlAy4AqA60PrrUTaczd&sz=w512','Ак Барс':'https://drive.google.com/thumbnail?id=1I09r6XwD-9L4r5ojPGKCHsJ5WGUyOFy1&sz=w512','Спартак':'https://drive.google.com/thumbnail?id=19kJ3uz-yyb1Z2y8qvRbFwuw_2kjUUD2f&sz=w512','Динамо СПБ':'https://drive.google.com/thumbnail?id=1x4KaAFMJ_qfmi26oVjnsc-huKpWtqBbh&sz=w512','Динамо-Джуниверс':'https://drive.google.com/thumbnail?id=1HTqvh6fg5ZzOLFwOtY62zucjnRZyOXmu&sz=w512','СКА-Стрельна':'https://drive.google.com/thumbnail?id=1DH_sKpyVZsh6vnt8Q1_ovBpDuVkPHrNh&sz=w512','АКМ':'https://drive.google.com/thumbnail?id=1NmPj1OwI3C1yuNmgt2XX57HbEiiDauB7&sz=w512','ЦСКА':'https://drive.google.com/thumbnail?id=1bT6o4afTqonyA05keLbe_nfQ78sAmNda&sz=w512','Армия СКА':'https://drive.google.com/thumbnail?id=14XZX2FRyR5x_aVkU2SMLhW-Emk0RUkTo&sz=w512','Нефтехимик':'https://drive.google.com/thumbnail?id=1csEdtjesEvgAFSsfnfhmWUnUE23Tnqeg&sz=w512','Северсталь':'https://drive.google.com/thumbnail?id=10xBTOFy_ps1G3LNaHV3WpbQkuZ74pjRn&sz=w512','Красная Машина Юниор':'https://drive.google.com/thumbnail?id=1qATM0WxWDCgYfemDQvhdy30Ub0sWSWWV&sz=w512'};
let DATA=null,ROSTERS={home:null,away:null},selectedLine=1,lastFetch=0,pollTimer=null,ageTimer=null;
const id=Number(new URL(location.href).searchParams.get('id'));
const $=s=>document.querySelector(s);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=x=>String(x||'').toLocaleLowerCase('ru-RU').replace(/[«»"']/g,'').replace(/ё/g,'е').replace(/\s+/g,' ').trim();
function logo(team){return team?.logo_url||LOGOS[team?.name]||''}
function teamBySide(side){return side==='away'?DATA?.away_team:DATA?.home_team}
function fmtDate(d,opts={day:'numeric',month:'long',year:'numeric'}){try{return new Date(d+'T12:00:00').toLocaleDateString('ru-RU',opts)}catch{return d||''}}
function fmtDay(d){try{return new Date(d+'T12:00:00').toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'short'})}catch{return d}}
function isNumericScore(m){return Number.isInteger(m?.home_score)&&Number.isInteger(m?.away_score)}
function scheduledStart(){const m=DATA?.match,t=String(m?.start_time||'').slice(0,5);if(!m?.game_date||!/^\d{2}:\d{2}$/.test(t))return NaN;return Date.parse(`${m.game_date}T${t}:00+03:00`)}
function state(){const live=DATA?.live,m=DATA?.match,db=String(m?.fhr_live_state||'').toUpperCase();if(live?.status==='FINAL'||m?.fhr_live_final_at||db==='FINAL')return'FINAL';const start=scheduledStart();if(Number.isFinite(start)&&Date.now()<start)return'SCHEDULED';if(live?.status==='ACTIVE'||['WATCHING','ERROR'].includes(db))return'ACTIVE';return'SCHEDULED'}
function score(){const st=state(),live=DATA?.live,m=DATA?.match;if(st!=='SCHEDULED'&&Array.isArray(live?.headline_score))return live.headline_score;if(isNumericScore(m)&&st==='FINAL')return[m.home_score,m.away_score];return null}
function livePeriod(){const l=DATA?.live;if(state()==='FINAL')return'FINAL';const txt=String(l?.status_text||'');if(/перерыв/i.test(txt))return'BREAK';return l?.current_period||'1'}
function stateLabel(){const st=state(),p=livePeriod();if(st==='FINAL')return'Матч завершён';if(st==='SCHEDULED')return'Матч не начался';if(p==='BREAK')return'Перерыв · LIVE';if(p==='OT')return'● LIVE · Овертайм';return`● LIVE · ${p||'1'} период`}
function periodScores(){if(state()==='SCHEDULED')return[];const l=DATA?.live,m=DATA?.match;const arr=Array.isArray(l?.period_scores)&&l.period_scores.length?l.period_scores:[[m?.p1_home,m?.p1_away],[m?.p2_home,m?.p2_away],[m?.p3_home,m?.p3_away],[m?.ot_home,m?.ot_away],[m?.so_home,m?.so_away]].filter(x=>Number.isInteger(x[0])&&Number.isInteger(x[1]));return arr}
function periodHtml(){const labels=['1 период','2 период','3 период','ОТ','Булл.'];const ps=periodScores();return labels.map((label,i)=>`<div class="period-chip"><span>${label}</span><strong>${ps[i]?`${ps[i][0]}:${ps[i][1]}`:'—'}</strong></div>`).join('')}
function gameDone(g){return String(g.fhr_live_state||'').toUpperCase()==='FINAL'||Boolean(g.fhr_live_final_at)||(Number.isInteger(g.home_score)&&Number.isInteger(g.away_score)&&g.home_score!==g.away_score)}
function gameLive(g){if(gameDone(g))return false;const t=String(g.start_time||'').slice(0,5),start=g.game_date&&/^\d{2}:\d{2}$/.test(t)?Date.parse(`${g.game_date}T${t}:00+03:00`):NaN;if(Number.isFinite(start)&&Date.now()<start)return false;return['WATCHING','ERROR'].includes(String(g.fhr_live_state||'').toUpperCase())}
function scheduleHtml(){const all=DATA.schedule||[],date=DATA.match.game_date,dates=[...new Set(all.map(x=>x.game_date))].sort(),idx=dates.indexOf(date),wanted=[date];if(idx>=0&&dates[idx+1])wanted.push(dates[idx+1]);const tabs=wanted.map((d,i)=>`<span class="day-tab ${i===0?'active':''}">${i===0?'Текущий игровой день':'Следующий игровой день'} · ${esc(fmtDay(d))}</span>`).join('');const games=all.filter(g=>wanted.includes(g.game_date)).map(g=>{const current=Number(g.id)===Number(DATA.match.id),done=gameDone(g),live=gameLive(g),score=done||live?`${g.home_score??0}:${g.away_score??0}`:g.start_time||'—';return`<a class="mini-game ${current?'current':''}" href="/match.html?id=${g.id}"><div class="mini-top"><span>${esc(fmtDay(g.game_date))} · №${g.game_no??'—'}</span><span class="mini-score ${live?'live-dot':''}">${live?'● ':''}${esc(score)}</span></div><div class="mini-teams"><div class="mini-team"><span>${esc(g.home_team.name)}</span>${done?`<b>${g.home_score}</b>`:''}</div><div class="mini-team"><span>${esc(g.away_team.name)}</span>${done?`<b>${g.away_score}</b>`:''}</div></div></a>`}).join('');return`<section class="dayrail wrap"><div class="dayrail-head"><strong>Матчи игрового дня</strong><span class="dayrail-note">Выберите матч, чтобы перейти в его LIVE-центр</span></div><div class="day-tabs">${tabs}</div><div class="game-strip">${games}</div></section>`}
function scoreboardHtml(){const m=DATA.match,h=DATA.home_team,a=DATA.away_team,s=score(),st=state(),place=[m.city,m.arena].filter(Boolean).join(' · '),date=fmtDate(m.game_date),hl=logo(h),al=logo(a);return`<section class="score-section wrap"><article class="score-card"><div class="match-kicker">${esc(DATA.stage?.name||'')} · ${esc(DATA.group?.name||DATA.group?.code||'')} · Матч №${m.game_no??'—'}</div><div class="score-grid"><div class="score-team"><div class="score-logo">${hl?`<img src="${esc(hl)}" alt="Логотип ${esc(h.name)}">`:''}</div><h1>${esc(h.name)}</h1><p>${esc(h.city||'')}</p></div><div class="score-center"><div class="match-state ${st==='ACTIVE'?'live':''}">${esc(stateLabel())}</div><div class="live-track ${st==='ACTIVE'?'show':''}"></div><div class="main-score ${s?'':'pending'}">${s?`${s[0]}:${s[1]}`:'— : —'}</div><div class="period-line">${periodHtml()}</div></div><div class="score-team"><div class="score-logo">${al?`<img src="${esc(al)}" alt="Логотип ${esc(a.name)}">`:''}</div><h1>${esc(a.name)}</h1><p>${esc(a.city||'')}</p></div></div><div class="score-meta"><span>${esc(date)} · ${esc(m.start_time||'Время уточняется')}</span><span>${esc(place||'Место проведения уточняется')}</span>${m.stream_url?`<a class="stream-btn" target="_blank" rel="noopener noreferrer" href="${esc(m.stream_url)}">▶ Смотреть трансляцию</a>`:''}<span id="freshness" class="freshness">Обновлено только что</span></div></article></section>`}
function playerForEvent(ev){const side=ev.side==='away'?'away':'home',list=(ROSTERS[side]||[]),n=Number(ev.number);let p=Number.isInteger(n)?list.find(x=>Number(x.number)===n):null;if(!p&&ev.player){const name=norm(ev.player);p=list.find(x=>norm(x.name)===name||norm(x.name).includes(name)||name.includes(norm(x.name)))||null}return p}
function photoHtml(ev){const p=playerForEvent(ev);const src=p?.photo_proxy||p?.photo||'';return src?`<img class="event-photo" src="${esc(src)}" alt="${esc(p.name)}" loading="lazy">`:''}
function actualScore(ev){if(!Array.isArray(ev.score))return null;return DATA.live?.orientation==='reverse'?[ev.score[1],ev.score[0]]:ev.score}
function goalNarrative(ev){const s=actualScore(ev),team=teamBySide(ev.side)?.name||'Команда';if(!s)return`${team} забрасывает шайбу`;const [h,a]=s,total=h+a,side=ev.side;if(total===1)return`${team} открывает счёт`;if(h===a)return`${team} сравнивает счёт`;const scorer=side==='home'?h:a,opp=side==='home'?a:h;if(scorer===opp+1)return`${team} выходит вперёд`;if(scorer>opp+1)return`${team} увеличивает преимущество`;if(scorer<opp)return`${team} сокращает отставание`;return`${team} забрасывает шайбу`}
function goalieLabels(events){const labels=new Map(),last={home:null,away:null};[...events].filter(e=>e.event_type==='GOALKEEPER').sort((a,b)=>(a.absolute_seconds??0)-(b.absolute_seconds??0)).forEach(e=>{if(e.empty_net){labels.set(e.key,'Пустые ворота');return}const side=e.side==='away'?'away':'home',cur=norm(e.player||'');if(last[side]&&last[side]!==cur)labels.set(e.key,'Смена вратаря');else labels.set(e.key,'В воротах');if(cur)last[side]=cur});return labels}
function onIceHtml(ev){if(!ev.on_ice)return'';const block=(side,title)=>{const list=ev.on_ice?.[side]||[];if(!list.length)return'';return`<div class="on-ice-team"><strong>${esc(title)}</strong><div class="ice-chips">${list.map(p=>`<span class="ice-chip">№${p.number} ${esc(p.name)}</span>`).join('')}</div></div>`};return`<details class="on-ice"><summary>Кто был на льду в момент события</summary><div class="on-ice-grid">${block('home',DATA.home_team.name)}${block('away',DATA.away_team.name)}</div></details>`}
function storedEvents(){return(DATA.stored_events||[]).map(e=>({key:`stored:${e.id}`,event_type:e.event_type,period:e.period,clock:e.clock,side:Number(e.team_id)===Number(DATA.away_team.id)?'away':Number(e.team_id)===Number(DATA.home_team.id)?'home':null,player:e.player,assistants:e.assistants,penalty_minutes:e.penalty_minutes,description:e.description,absolute_seconds:null,score:e.source_payload?.raw_score||null,power_play:e.source_payload?.power_play||false}))}
function eventFeedHtml(){let evs=Array.isArray(DATA.live?.events)&&DATA.live.events.length?DATA.live.events:storedEvents();if(!evs.length)return'<div class="empty">Событий матча пока нет. LIVE-протокол появится здесь автоматически после начала игры.</div>';const gl=goalieLabels(evs);return`<div class="timeline">${evs.map(ev=>{const type=String(ev.event_type||'NOTE').toUpperCase(),team=teamBySide(ev.side),l=logo(team),num=ev.number?`№${ev.number} `:'',period=ev.period==='OT'?'ОТ':`${ev.period||'—'} период`,score=actualScore(ev),photo=photoHtml(ev);let label='Событие',title=ev.player||team?.name||'Матч',desc=ev.description||'',cls='';if(type==='GOAL'){cls='goal';label='Гол';title=`${num}${ev.player||''}`.trim()||team?.name;desc=goalNarrative(ev)+(ev.assistants?` · Передачи: ${ev.assistants}`:'')+(ev.power_play?' · В большинстве':'')}else if(type==='PENALTY'){cls='penalty';label='Удаление';title=`${num}${ev.player||'Командный штраф'}`.trim();desc=[ev.penalty_minutes?`${ev.penalty_minutes} мин.`:'',ev.description||''].filter(Boolean).join(' · ')}else if(type==='GOALKEEPER'){cls='goalkeeper';label=gl.get(ev.key)||'Вратарь';title=`${num}${ev.player||'Вратарь'}`.trim();desc=team?.name||''}else if(type==='TIMEOUT'){cls='goalkeeper';label='Тайм-аут';title=team?.name||'Команда';desc='Тайм-аут команды'}return`<article class="event-card ${cls}"><div class="event-time"><strong>${esc(ev.clock||'—')}</strong><span>${esc(period)}</span></div>${l?`<img class="event-logo" src="${esc(l)}" alt="">`:'<span></span>'}<div class="event-main">${photo}<div class="event-copy"><span class="event-label">${esc(label)}</span><strong>${esc(title)}</strong><p>${esc(desc)}</p></div></div><div class="event-score">${score?`${score[0]}:${score[1]}`:''}</div>${type==='GOAL'?onIceHtml(ev):''}</article>`}).join('')}</div>`}
async function loadFallbackRoster(side){const team=teamBySide(side);if(!team)return[];try{const r=await fetch(`${ROSTER}?team=${team.id}&v=2`,{cache:'no-store'});if(!r.ok)return[];const b=await r.json();return(b.players||[]).map(p=>({...p,photo_proxy:p.photo?`${ROSTER}?photo=${encodeURIComponent(p.photo)}`:''}))}catch{return[]}}
async function prepareRosters(){for(const side of ['home','away']){const official=DATA.lineups?.[side]||[];if(official.length>=5)ROSTERS[side]=official;else ROSTERS[side]=await loadFallbackRoster(side)}}
function rosterGroup(list,pos){return list.filter(p=>(p.position||p.pos)==pos||p.pos===pos)}
function rosterRows(list){return list.map(p=>`<div class="player-row"><span class="player-num">${p.number??'—'}</span><span class="player-avatar">${p.photo_proxy||p.photo?`<img src="${esc(p.photo_proxy||p.photo)}" alt="${esc(p.name)}" loading="lazy">`:(p.number??'')}</span><span class="player-name">${esc(p.name)}<small>${p.position==='G'||p.pos==='G'?'Вратарь':p.position==='D'||p.pos==='D'?'Защитник':p.position==='F'||p.pos==='F'?'Нападающий':''}</small></span><span class="player-tag">${esc(p.goalie_role||p.captain||(p.line?`${p.line} зв.`:''))}</span></div>`).join('')}
function rosterTeamHtml(side){const team=teamBySide(side),list=ROSTERS[side]||[],l=logo(team),official=(DATA.lineups?.[side]||[]).length>=5;const groups=[['G','Вратари'],['D','Защитники'],['F','Нападающие'],['U','Игроки']];return`<article class="roster-team"><div class="roster-head">${l?`<img src="${esc(l)}" alt="">`:''}<div><strong>${esc(team.name)}</strong><div class="roster-source">${official?'Состав на матч · ФХР':'Актуальная заявка · ФХР'}</div></div></div>${groups.map(([code,title])=>{const xs=rosterGroup(list,code);return xs.length?`<div class="roster-group-title">${title}</div>${rosterRows(xs)}`:''}).join('')}</article>`}
function rinkPlayer(p,cls,away=false){if(!p)return'';const src=p.photo_proxy||p.photo||'';const surname=String(p.name||'').split(' ')[0];return`<div class="rink-player ${away?'away':''} ${cls}"><div class="rink-avatar">${src?`<img src="${esc(src)}" alt="${esc(p.name)}">`:''}<span class="rink-number">${p.number??'—'}</span></div><div class="rink-name">${esc(surname)}</div></div>`}
function linePlayers(side,line){const list=DATA.lineups?.[side]||[],d=list.filter(p=>p.position==='D'&&Number(p.line)===line).slice(0,2),f=list.filter(p=>p.position==='F'&&Number(p.line)===line).slice(0,3),g=list.find(p=>p.position==='G'&&p.goalie_role==='ОВ')||list.find(p=>p.position==='G');return{d,f,g}}
function availableLines(){const h=DATA.lineups?.home||[],a=DATA.lineups?.away||[];return[1,2,3,4].filter(n=>h.some(p=>Number(p.line)===n)||a.some(p=>Number(p.line)===n))}
function rinkHtml(){const lines=availableLines();if(!lines.length)return'<div class="empty">ФХР ещё не опубликовала сочетания на этот матч. Как только появятся номера звеньев, хоккейная карта соберётся автоматически.</div>';if(!lines.includes(selectedLine))selectedLine=lines[0];const h=linePlayers('home',selectedLine),a=linePlayers('away',selectedLine),enough=h.d.length+h.f.length+a.d.length+a.f.length;const buttons=lines.map(n=>`<button class="line-tab ${n===selectedLine?'active':''}" type="button" data-line="${n}">${n}-е сочетание</button>`).join('');return`<div class="rink-shell"><div class="line-tabs">${buttons}</div>${enough?`<div class="rink"><span class="center-dot"></span><span class="faceoff f1"></span><span class="faceoff f2"></span><span class="faceoff f3"></span><span class="faceoff f4"></span>${rinkPlayer(h.d[0],'pos-hd1')}${rinkPlayer(h.d[1],'pos-hd2')}${rinkPlayer(h.f[0],'pos-hf1')}${rinkPlayer(h.f[1],'pos-hf2')}${rinkPlayer(h.f[2],'pos-hf3')}${rinkPlayer(a.d[0],'pos-ad1',true)}${rinkPlayer(a.d[1],'pos-ad2',true)}${rinkPlayer(a.f[0],'pos-af1',true)}${rinkPlayer(a.f[1],'pos-af2',true)}${rinkPlayer(a.f[2],'pos-af3',true)}</div><div class="goalies"><div class="goalie-card">${h.g?.photo_proxy||h.g?.photo?`<img src="${esc(h.g.photo_proxy||h.g.photo)}" alt="">`:''}<div><strong>${esc(DATA.home_team.name)}</strong>Вратарь: ${h.g?`№${h.g.number} ${esc(h.g.name)}`:'не указан'}</div></div><div class="goalie-card"><div><strong>${esc(DATA.away_team.name)}</strong>Вратарь: ${a.g?`№${a.g.number} ${esc(a.g.name)}`:'не указан'}</div>${a.g?.photo_proxy||a.g?.photo?`<img src="${esc(a.g.photo_proxy||a.g.photo)}" alt="">`:''}</div></div><div class="rink-legend"><span>${esc(DATA.home_team.name)} · слева</span><span>${selectedLine}-е сочетание</span><span>${esc(DATA.away_team.name)} · справа</span></div>`:'<div class="empty">Для выбранного сочетания ФХР пока не указала полный комплект игроков.</div>'}</div>`}
function bodyHtml(){return`${scheduleHtml()}${scoreboardHtml()}<div class="sticky-tabs"><nav class="wrap section-tabs"><a href="#live">Ход матча</a><a href="#rosters">Составы</a><a href="#lines">Пятёрки на льду</a></nav></div><section class="section wrap" id="live"><div class="section-head"><div><div class="section-kicker">LIVE · протокол</div><h2 class="section-title">Ход матча</h2></div><div class="section-note">Голы выделены зелёным, удаления — красным, события с вратарями — синим. Данные обновляются автоматически.</div></div>${eventFeedHtml()}</section><section class="section wrap" id="rosters"><div class="section-head"><div><div class="section-kicker">Заявка на игру</div><h2 class="section-title">Составы команд</h2></div><div class="section-note">Приоритет — состав конкретного матча с ФХР. До его публикации показывается актуальная заявка команды.</div></div><div class="roster-grid">${rosterTeamHtml('home')}${rosterTeamHtml('away')}</div></section><section class="section wrap" id="lines"><div class="section-head"><div><div class="section-kicker">Тактика</div><h2 class="section-title">Пятёрки на хоккейной карте</h2></div><div class="section-note">Сочетания формируются только из официально опубликованных ФХР номеров звеньев — ничего не расставляем вручную.</div></div><div id="rinkRoot">${rinkHtml()}</div></section>`}
function updateAge(){const el=$('#freshness');if(!el||!lastFetch)return;const sec=Math.max(0,Math.floor((Date.now()-lastFetch)/1000));el.textContent=sec<5?'Обновлено только что':`Обновлено ${sec} сек. назад`}
async function load({quiet=false}={}){if(!Number.isInteger(id)||id<1){$('#main').innerHTML='<div class="wrap status-page">Матч не найден.</div>';return}try{const r=await fetch(`${EDGE}?match_id=${id}&_=${Date.now()}`,{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error||'Не удалось загрузить матч');DATA=b;lastFetch=Date.now();document.title=`${DATA.home_team.name} — ${DATA.away_team.name} · Матч-центр`;await prepareRosters();$('#main').innerHTML=bodyHtml();bind();updateAge();schedulePoll()}catch(e){if(!quiet||!DATA)$('#main').innerHTML=`<div class="wrap status-page">${esc(e.message||'Не удалось загрузить матч-центр.')}</div>`;schedulePoll(true)}}
function bind(){document.querySelectorAll('[data-line]').forEach(b=>b.onclick=()=>{selectedLine=Number(b.dataset.line);const root=$('#rinkRoot');if(root){root.innerHTML=rinkHtml();bind()}})}
function schedulePoll(error=false){clearTimeout(pollTimer);const st=state(),delay=error?30000:st==='ACTIVE'?15000:st==='SCHEDULED'?30000:60000;pollTimer=setTimeout(()=>load({quiet:true}),delay)}
ageTimer=setInterval(updateAge,1000);
load();
})();