(()=>{
  const API='https://wcucbtdfkghjirpbqzzk.supabase.co/functions/v1/russian-cup';
  const TEAM_LOGOS={
    'Динамо Москва':'https://drive.google.com/thumbnail?id=1I3KuJZEajmksDKtoBsdj4h_75fU0e_KY&sz=w512','МАХ':'https://drive.google.com/thumbnail?id=1Veii4NYgKc06nRtxKmCRQv1YCE164YZP&sz=w512','Торпедо':'https://drive.google.com/thumbnail?id=17NYLCFaSrX6q4g0T7jhBnmidrI1JzKl9&sz=w512','Локомотив':'https://drive.google.com/thumbnail?id=1D6wJnaawN4kMt-1ZWTSvf-trYkslzyKi&sz=w512','Авангард':'https://drive.google.com/thumbnail?id=1y6CZfZSXYDVqCAjOvv6xB_7Fwu1AQwvn&sz=w512','Локомотив 2004':'https://drive.google.com/thumbnail?id=1sq7UHtBq_xiexekxmzWawF3yVTaEl-J-&sz=w512','Крылья Советов':'https://drive.google.com/thumbnail?id=1n6ViHZhkRvq_R_Ul1PEHnFnX7HVNk6-p&sz=w512','Сибирь':'https://drive.google.com/thumbnail?id=1Xul8VXC7juk2NHQfb28Cl9Jt_Kj0Obw-&sz=w512','Лада':'https://drive.google.com/thumbnail?id=15mcwMoXT7OaH46jj8w90PCeTtJY54UAF&sz=w512','Трактор':'https://drive.google.com/thumbnail?id=1qWTRWy-p36RDSMlAy4AqA60PrrUTaczd&sz=w512','Ак Барс':'https://drive.google.com/thumbnail?id=1I09r6XwD-9L4r5ojPGKCHsJ5WGUyOFy1&sz=w512','Спартак':'https://drive.google.com/thumbnail?id=19kJ3uz-yyb1Z2y8qvRbFwuw_2kjUUD2f&sz=w512','Динамо СПБ':'https://drive.google.com/thumbnail?id=1x4KaAFMJ_qfmi26oVjnsc-huKpWtqBbh&sz=w512','СКА-Стрельна':'https://drive.google.com/thumbnail?id=1DH_sKpyVZsh6vnt8Q1_ovBpDuVkPHrNh&sz=w512','АКМ':'https://drive.google.com/thumbnail?id=1NmPj1OwI3C1yuNmgt2XX57HbEiiDauB7&sz=w512','ЦСКА':'https://drive.google.com/thumbnail?id=1bT6o4afTqonyA05keLbe_nfQ78sAmNda&sz=w512','Армия СКА':'https://drive.google.com/thumbnail?id=14XZX2FRyR5x_aVkU2SMLhW-Emk0RUkTo&sz=w512','Нефтехимик':'https://drive.google.com/thumbnail?id=1csEdtjesEvgAFSsfnfhmWUnUE23Tnqeg&sz=w512','Северсталь':'https://drive.google.com/thumbnail?id=10xBTOFy_ps1G3LNaHV3WpbQkuZ74pjRn&sz=w512','Красная Машина Юниор':'https://drive.google.com/thumbnail?id=1qATM0WxWDCgYfemDQvhdy30Ub0sWSWWV&sz=w512'
  };
  const TEAM_META={
    'Авангард':{
      city:'Омск',
      arena:'G-Drive Арена · Омск, ул. Лукашевича, 35',
      socials:{
        vk:'https://vk.com/hcavangard',
        tg:'https://t.me/omskiyavangard',
        max:'https://max.ru/omskiyavangard',
        web:'https://hawk.ru/'
      }
    },
    'Динамо Москва':{city:'Москва'},'МАХ':{city:'Москва'},'Торпедо':{city:'Нижний Новгород'},'Локомотив':{city:'Ярославль'},'Локомотив 2004':{city:'Ярославль'},'Крылья Советов':{city:'Москва'},'Сибирь':{city:'Новосибирск'},'Лада':{city:'Тольятти'},'Трактор':{city:'Челябинск'},'Ак Барс':{city:'Казань'},'Спартак':{city:'Москва'},'Динамо СПБ':{city:'Санкт-Петербург'},'СКА-Стрельна':{city:'Санкт-Петербург'},'АКМ':{city:'Новомосковск'},'ЦСКА':{city:'Москва'},'Армия СКА':{city:'Санкт-Петербург'},'Нефтехимик':{city:'Нижнекамск'},'Северсталь':{city:'Череповец'},'Красная Машина Юниор':{city:'Красногорск'}
  };
  let CURRENT_DATA=null;
  const $=s=>document.querySelector(s);
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const done=m=>Number.isInteger(m.home_score)&&Number.isInteger(m.away_score)&&m.home_score!==m.away_score;
  async function get(path){const r=await fetch(API+path,{cache:'no-store'});if(!r.ok)throw Error(await r.text());return r.json()}
  function fmtDate(x){return new Date(x+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}
  function time(m){return String(m.start_time||'').slice(0,5)}
  function finish(m){return m.finish_type==='OT'?'ОТ':m.finish_type==='SO'?'буллиты':''}
  function pts(m,id,s){if(!done(m))return 0;const winner=(m.home_score>m.away_score?m.home_team_id:m.away_team_id)===id;return winner?s.win_points:(m.finish_type==='REG'?s.regulation_loss_points:s.ot_loss_points)}
  function row(team,group,data){const ms=data.matches.filter(m=>m.group_id===group.id&&[m.home_team_id,m.away_team_id].includes(team.id));let o={gp:0,w:0,rw:0,ow:0,l:0,rl:0,ol:0,gf:0,ga:0,gd:0,pts:0};for(const m of ms){if(!done(m))continue;o.gp++;const home=m.home_team_id===team.id;const f=home?m.home_score:m.away_score,a=home?m.away_score:m.home_score;o.gf+=f;o.ga+=a;o.pts+=pts(m,team.id,data.settings);if(f>a){o.w++;m.finish_type==='REG'?o.rw++:o.ow++}else{o.l++;m.finish_type==='REG'?o.rl++:o.ol++}}o.gd=o.gf-o.ga;return o}
  function groupRows(group,data){return CupStandings.groupRows(data,group).map(r=>({...r,team:data.teams.find(t=>String(t.id)===String(r.team_id))}))}
  function logo(name,cls=''){const t=CURRENT_DATA?.teams?.find(x=>x.name===name),src=t?.logo_url||TEAM_LOGOS[name];return src?`<img class="${cls}" src="${src}" alt="Логотип ${esc(name)}">`:''}
  function initials(name){return name==='Участник не определен'?'?':name.split(/\s+/).map(x=>x[0]).join('').slice(0,3).toUpperCase()}
  function socialIcon(type){
    if(type==='vk')return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3.6 7.2h3c.2 0 .4.1.5.4.6 1.7 1.5 3.1 2.4 4.1.5.5.8.7 1 .8.1 0 .2-.2.2-.5V7.7c0-.3.1-.5.4-.5h2.8c.3 0 .5.2.5.5v3.8c0 .3.1.5.2.5.2 0 .5-.2.9-.6 1-1.1 1.8-2.5 2.3-4 .1-.2.3-.3.5-.3h3c.5 0 .7.3.5.7-.5 1.5-1.8 3.4-3.5 5.2-.2.2-.2.5 0 .7 1.8 1.6 3 3.2 3.6 4.2.3.5.1.8-.4.8h-3.3c-.3 0-.5-.1-.7-.4-.8-1.1-1.6-2-2.4-2.6-.3-.2-.5-.1-.5.3v2.2c0 .3-.2.5-.5.5h-1.5c-4.3 0-7.2-2.9-8.7-10.8-.1-.5.1-.7.6-.7Z"/></svg>';
    if(type==='tg')return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21.4 4.1 18.3 19c-.2 1.1-.9 1.4-1.8.9l-4.7-3.5-2.3 2.2c-.3.3-.5.5-1 .5l.3-4.8 8.8-7.9c.4-.3-.1-.5-.6-.2L6.2 13l-4.7-1.5c-1-.3-1-1 .2-1.5L20 3c.9-.3 1.6.2 1.4 1.1Z"/></svg>';
    if(type==='max')return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5.2c0-.7.6-1.2 1.2-1.2h11.6c.7 0 1.2.6 1.2 1.2v10.6c0 .7-.6 1.2-1.2 1.2h-5l-3.5 3v-3H6.2c-.7 0-1.2-.6-1.2-1.2V5.2Zm3.1 3.2 2.6 5 1.3-2.5 1.3 2.5 2.6-5h-1.8l-.8 1.8-1.3-2.5-1.3 2.5-.8-1.8H8.1Z"/></svg>';
    return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm6.9 6h-3.1a15.8 15.8 0 0 0-1.4-3.3A8.1 8.1 0 0 1 18.9 8ZM12 4c.9 1.1 1.6 2.4 2 4h-4c.4-1.6 1.1-2.9 2-4ZM9.6 4.7A15.8 15.8 0 0 0 8.2 8H5.1a8.1 8.1 0 0 1 4.5-3.3ZM4 12c0-.7.1-1.4.3-2h3.5a16.7 16.7 0 0 0 0 4H4.3A8.4 8.4 0 0 1 4 12Zm1.1 4h3.1a15.8 15.8 0 0 0 1.4 3.3A8.1 8.1 0 0 1 5.1 16ZM12 20c-.9-1.1-1.6-2.4-2-4h4c-.4 1.6-1.1 2.9-2 4Zm2.4-.7a15.8 15.8 0 0 0 1.4-3.3h3.1a8.1 8.1 0 0 1-4.5 3.3ZM16.2 14a14.9 14.9 0 0 0 0-4h3.5a8.4 8.4 0 0 1 0 4h-3.5ZM14.3 10a13 13 0 0 1 0 4H9.7a13 13 0 0 1 0-4h4.6Z"/></svg>';
  }
  function renderSocials(meta){const labels={vk:'ВКонтакте',tg:'Telegram',max:'MAX',web:'Официальный сайт'},s=meta.socials||{};$('#socials').innerHTML=['vk','tg','max','web'].filter(k=>s[k]).map(k=>`<a class="social-link" href="${s[k]}" target="_blank" rel="noopener noreferrer" aria-label="${labels[k]}" title="${labels[k]}">${socialIcon(k)}</a>`).join('')}
  function renderNext(team,data,ms){const now=new Date();const upcoming=ms.filter(m=>!done(m)).sort((a,b)=>a.game_date.localeCompare(b.game_date)||time(a).localeCompare(time(b))||(a.game_no||0)-(b.game_no||0));const m=upcoming[0];if(!m){$('#nextMatch').innerHTML='<div class="empty">Следующих матчей в текущем туре нет.</div>';return}const home=data.teams.find(t=>t.id===m.home_team_id),away=data.teams.find(t=>t.id===m.away_team_id),place=[m.city,m.arena].filter(Boolean).join(' · ');$('#nextMatch').innerHTML=`<a class="next-match" href="/?match=${m.id}"><div class="next-team">${logo(home.name)}<span>${esc(home.name)}</span></div><div class="next-vs">—</div><div class="next-team away"><span>${esc(away.name)}</span>${logo(away.name)}</div><div class="next-meta"><strong>${fmtDate(m.game_date)} · ${time(m)||'—'}</strong><span>${esc(place||'Место уточняется')}<br>Матч №${m.game_no??'—'}</span></div></a>`}
  function renderMatches(team,data,ms){const sorted=[...ms].sort((a,b)=>a.game_date.localeCompare(b.game_date)||time(a).localeCompare(time(b))||(a.game_no||0)-(b.game_no||0));$('#matches').innerHTML=sorted.map(m=>{const home=data.teams.find(t=>t.id===m.home_team_id),away=data.teams.find(t=>t.id===m.away_team_id),g=data.groups.find(x=>x.id===m.group_id),place=[m.city,m.arena].filter(Boolean).join(' · ');return `<a class="match-row" href="/?match=${m.id}"><div class="match-info"><strong>${esc(g?.code||'')}</strong><br>${fmtDate(m.game_date)}${time(m)?'<br>'+time(m):''}</div><div class="match-team">${esc(home.name)}</div><div class="match-score"><strong>${done(m)?m.home_score+':'+m.away_score:'—'}</strong><span>${done(m)?finish(m):'предстоит'}</span></div><div class="match-team away">${esc(away.name)}</div><div class="match-place">${esc(place||'Место уточняется')}</div></a>`}).join('')||'<div class="empty">Матчи команды пока не добавлены.</div>'}
  function renderForm(team,ms){const finished=ms.filter(done).sort((a,b)=>b.game_date.localeCompare(a.game_date)||((b.game_no||0)-(a.game_no||0))).slice(0,5);$('#form').innerHTML=finished.reverse().map(m=>{const home=m.home_team_id===team.id,f=home?m.home_score:m.away_score,a=home?m.away_score:m.home_score,w=f>a;return `<span class="form-pill ${w?'win':'loss'}" title="${f}:${a}">${w?'В':'П'}</span>`}).join('')}
  function injectPositionStyle(){
    if(document.getElementById('team-position-history-style'))return;
    const s=document.createElement('style');s.id='team-position-history-style';s.textContent=`
      .team-stage-tools{display:flex;align-items:center;gap:10px;flex-wrap:wrap;justify-content:flex-end}.team-stage-select{appearance:none;min-width:132px;border:1px solid var(--line);background:#0a192b;color:#dfeaf6;border-radius:9px;padding:8px 28px 8px 10px;font:inherit;font-size:10px;font-weight:850;outline:none}.team-stage-select:focus{border-color:rgba(127,198,255,.45)}
      .position-history-card{border:1px solid var(--line);border-radius:12px;background:linear-gradient(180deg,rgba(15,33,55,.93),rgba(8,22,38,.96));padding:16px;overflow:hidden}.position-history-meta{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:10px;color:#8195a9;font-size:9px}.position-history-meta strong{color:#dfeaf5;font-size:12px}.position-chart-scroll{overflow-x:auto}.position-chart{display:block;width:100%;min-width:560px;height:auto}.position-grid{stroke:rgba(255,255,255,.07);stroke-width:1}.position-axis-label{fill:#71859a;font-size:9px}.position-line{fill:none;stroke:#7fc6ff;stroke-width:3;stroke-linecap:round;stroke-linejoin:round}.position-point{fill:#07111f;stroke:#7fc6ff;stroke-width:3}.position-point-last{fill:#7fc6ff;stroke:#dff3ff}.position-place-label{fill:#dff2ff;font-size:10px;font-weight:900}.position-date-label{fill:#70849a;font-size:8px}.position-empty{padding:25px;border:1px dashed var(--line);border-radius:10px;color:#8396aa;text-align:center;font-size:10px;line-height:1.55}
      @media(max-width:720px){.team-stage-tools{width:100%;justify-content:space-between}.team-stage-select{flex:1}.position-history-card{padding:12px}}
    `;document.head.appendChild(s)
  }
  function playedForHistory(m){return done(m)||String(m?.technical_result_type||'NONE')!=='NONE'||String(m?.fhr_live_state||'').toUpperCase()==='FINAL'}
  function renderPositionHistory(team,group,data){
    const root=$('#positionHistoryChart');if(!root)return;if(!group){root.innerHTML='<div class="position-empty">Команда пока не распределена в группу этого тура.</div>';return}
    const groupMatches=data.matches.filter(m=>Number(m.group_id)===Number(group.id)),dates=[...new Set(groupMatches.filter(playedForHistory).map(m=>m.game_date))].sort();
    if(!dates.length){root.innerHTML='<div class="position-empty">Динамика появится после первого завершённого игрового дня команды и её группы.</div>';return}
    const nTeams=Math.max(2,data.memberships.filter(m=>Number(m.group_id)===Number(group.id)).length||5);
    const points=dates.map(date=>{const snap={...data,matches:data.matches.filter(m=>Number(m.group_id)!==Number(group.id)||String(m.game_date)<=date)};const rows=CupStandings.groupRows(snap,group),r=rows.find(x=>Number(x.team_id)===Number(team.id));return{date,place:Number(r?.place)||nTeams,pts:Number(r?.pts)||0}}).filter(Boolean);
    const W=900,H=250,L=54,R=25,T=22,B=48,innerW=W-L-R,innerH=H-T-B,x=(i)=>points.length===1?L+innerW/2:L+i*innerW/(points.length-1),y=(place)=>T+(Math.max(1,Math.min(nTeams,place))-1)*innerH/(nTeams-1),coords=points.map((p,i)=>`${x(i)},${y(p.place)}`).join(' ');
    const grids=Array.from({length:nTeams},(_,i)=>{const yy=y(i+1);return`<line class="position-grid" x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}"></line><text class="position-axis-label" x="${L-18}" y="${yy+3}">${i+1}</text>`}).join('');
    const nodes=points.map((p,i)=>{const xx=x(i),yy=y(p.place),last=i===points.length-1,date=new Date(p.date+'T12:00:00').toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit'});return`<g><circle class="position-point ${last?'position-point-last':''}" cx="${xx}" cy="${yy}" r="${last?6:5}"><title>${date} · ${p.place} место · ${p.pts} очк.</title></circle><text class="position-place-label" x="${xx}" y="${yy-11}" text-anchor="middle">#${p.place}</text><text class="position-date-label" x="${xx}" y="${H-18}" text-anchor="middle">${date}</text></g>`}).join('');
    const last=points[points.length-1];
    root.innerHTML=`<article class="position-history-card"><div class="position-history-meta"><strong>${esc(group.name||group.code||'Группа')}</strong><span>Последняя точка: ${last.place} место · ${last.pts} очк.</span></div><div class="position-chart-scroll"><svg class="position-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="График изменения места команды в группе">${grids}<polyline class="position-line" points="${coords}"></polyline>${nodes}</svg></div></article>`
  }
  async function init(){try{
    const q=new URL(location.href).searchParams,id=Number(q.get('team'));if(!id)throw Error('Команда не выбрана');
    const catalog=await get('/api/catalog'),tournament=catalog.tournaments?.[0];if(!tournament)throw Error('Турнир не найден');
    const stages=(catalog.stages||[]).filter(s=>Number(s.tournament_id)===Number(tournament.id)).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)),requestedStage=Number(q.get('stage')),stage=stages.find(s=>Number(s.id)===requestedStage)||stages[0];if(!stage)throw Error('Этап не найден');
    const data=await get('/api/data?tournament_slug='+encodeURIComponent(tournament.slug)+'&stage_id='+encodeURIComponent(stage.id)),team=data.teams.find(t=>Number(t.id)===id);if(!team)throw Error('Команда не найдена');
    CURRENT_DATA=data;
    const fallback=TEAM_META[team.name]||{},arenas=Array.isArray(team.arenas)?team.arenas:[],arenaText=arenas.length?arenas.map(a=>[a.name,a.address].filter(Boolean).join(' — ')).join(' · '):(fallback.arena||''),meta={city:team.city||fallback.city||'',arena:arenaText,hero:team.hero_image_url||'',socials:{vk:team.vk_url||fallback.socials?.vk||'',tg:team.telegram_url||fallback.socials?.tg||'',max:team.max_url||fallback.socials?.max||'',web:team.website_url||fallback.socials?.web||''}},membership=data.memberships.find(x=>x.team_id===team.id),group=data.groups.find(g=>g.id===membership?.group_id),rows=group?groupRows(group,data):[],teamRow=rows.find(r=>r.team.id===team.id)||{gp:0,w:0,l:0,gf:0,ga:0,gd:0,pts:0,place:'—'},allRows=CupStandings.overall(data),overallPlace=allRows.findIndex(r=>String(r.team_id)===String(team.id))+1;
    const ms=data.matches.filter(m=>[m.home_team_id,m.away_team_id].includes(team.id));
    const tourLabel=String(data.stage?.name||'1 тур').replace(/^1-й тур$/i,'1 тур'),groupLabel=group?.code||group?.name||'—';
    document.title=team.name+' · Кубок России U16';$('#season').textContent=data.tournament.season||'2026/27';$('#teamKicker').textContent=tourLabel+' • группа '+groupLabel;$('#teamName').textContent=team.name;$('#teamArena').textContent=meta.arena||((meta.city?meta.city+' · ':'')+'адрес арены будет добавлен');const hero=$('#teamHeroBg');if(hero){hero.style.backgroundImage=meta.hero?`url("${meta.hero.replace(/"/g,'%22')}")`:'';hero.classList.toggle('has-image',Boolean(meta.hero))}
    const src=team.logo_url||TEAM_LOGOS[team.name];if(src){$('#teamLogo').src=src;$('#teamLogo').alt='Логотип '+team.name;$('#teamLogo').onerror=()=>{$('#teamLogo').style.display='none';$('#teamLogoFallback').style.display='grid';$('#teamLogoFallback').textContent=initials(team.name)}}else{$('#teamLogo').style.display='none';$('#teamLogoFallback').style.display='grid';$('#teamLogoFallback').textContent=initials(team.name)}
    renderSocials(meta);$('#groupName').textContent=group?.name||group?.code||'—';$('#groupPlace').textContent=teamRow.place||'—';const stageSelect=$('#teamStageSelect');if(stageSelect){stageSelect.innerHTML=stages.map(s=>`<option value="${s.id}" ${Number(s.id)===Number(stage.id)?'selected':''}>${esc(s.name)}</option>`).join('');stageSelect.onchange=()=>{const u=new URL(location.href);u.searchParams.set('stage',stageSelect.value);location.href=u.toString()}};
    $('#statsGrid').innerHTML=`<div class="stat-card"><strong>${overallPlace||'—'}</strong><span>место в общей таблице</span></div><div class="stat-card"><strong>${teamRow.gp}</strong><span>игр</span></div><div class="stat-card"><strong>${teamRow.w}</strong><span>побед</span></div><div class="stat-card"><strong>${teamRow.l}</strong><span>поражений</span></div><div class="stat-card"><strong>${teamRow.gf}:${teamRow.ga}</strong><span>шайбы</span></div><div class="stat-card"><strong>${teamRow.pts}</strong><span>очков</span></div>`;
    renderForm(team,ms);renderPositionHistory(team,group,data);renderNext(team,data,ms);renderMatches(team,data,ms);
  }catch(e){console.error(e);$('#teamName').textContent='Команда не найдена';$('#teamArena').textContent='Вернитесь к списку команд и выберите нужную карточку.';$('#nextMatch').innerHTML='<div class="empty">Не удалось загрузить данные команды.</div>';$('#matches').innerHTML=''}}
  injectPositionStyle();init();
})();
