(()=>{
  const API='https://wcucbtdfkghjirpbqzzk.supabase.co/functions/v1/russian-cup';
  const TEAM_LOGOS={
    'Динамо Москва':'https://drive.google.com/thumbnail?id=1I3KuJZEajmksDKtoBsdj4h_75fU0e_KY&sz=w512','МАХ':'https://drive.google.com/thumbnail?id=1Veii4NYgKc06nRtxKmCRQv1YCE164YZP&sz=w512','Торпедо':'https://drive.google.com/thumbnail?id=17NYLCFaSrX6q4g0T7jhBnmidrI1JzKl9&sz=w512','Локомотив':'https://drive.google.com/thumbnail?id=1D6wJnaawN4kMt-1ZWTSvf-trYkslzyKi&sz=w512','Авангард':'https://drive.google.com/thumbnail?id=1y6CZfZSXYDVqCAjOvv6xB_7Fwu1AQwvn&sz=w512','Локомотив 2004':'https://drive.google.com/thumbnail?id=1sq7UHtBq_xiexekxmzWawF3yVTaEl-J-&sz=w512','Крылья Советов':'https://drive.google.com/thumbnail?id=1n6ViHZhkRvq_R_Ul1PEHnFnX7HVNk6-p&sz=w512','Сибирь':'https://drive.google.com/thumbnail?id=1Xul8VXC7juk2NHQfb28Cl9Jt_Kj0Obw-&sz=w512','Лада':'https://drive.google.com/thumbnail?id=15mcwMoXT7OaH46jj8w90PCeTtJY54UAF&sz=w512','Трактор':'https://drive.google.com/thumbnail?id=1qWTRWy-p36RDSMlAy4AqA60PrrUTaczd&sz=w512','Ак Барс':'https://drive.google.com/thumbnail?id=1I09r6XwD-9L4r5ojPGKCHsJ5WGUyOFy1&sz=w512','Спартак':'https://drive.google.com/thumbnail?id=19kJ3uz-yyb1Z2y8qvRbFwuw_2kjUUD2f&sz=w512','Динамо СПБ':'https://drive.google.com/thumbnail?id=1x4KaAFMJ_qfmi26oVjnsc-huKpWtqBbh&sz=w512','СКА-Стрельна':'https://drive.google.com/thumbnail?id=1DH_sKpyVZsh6vnt8Q1_ovBpDuVkPHrNh&sz=w512','АКМ':'https://drive.google.com/thumbnail?id=1NmPj1OwI3C1yuNmgt2XX57HbEiiDauB7&sz=w512','ЦСКА':'https://drive.google.com/thumbnail?id=1bT6o4afTqonyA05keLbe_nfQ78sAmNda&sz=w512','Армия СКА':'https://drive.google.com/thumbnail?id=14XZX2FRyR5x_aVkU2SMLhW-Emk0RUkTo&sz=w512','Нефтехимик':'https://drive.google.com/thumbnail?id=1csEdtjesEvgAFSsfnfhmWUnUE23Tnqeg&sz=w512','Северсталь':'https://drive.google.com/thumbnail?id=10xBTOFy_ps1G3LNaHV3WpbQkuZ74pjRn&sz=w512','Красная Машина Юниор':'https://drive.google.com/thumbnail?id=1qATM0WxWDCgYfemDQvhdy30Ub0sWSWWV&sz=w512'
  };
  const TEAM_META={
    'Авангард':{
      city:'Омск',
      arena:'G-Drive Арена · Омск, ул. Лукашевича, 35',
      socials:{
        vk:'https://vk.com/hcavangard',
        tg:'https://t.me/omskiyavangard',
        max:'https://max.ru/omskiyavangard',
        web:'https://hawk.ru/'
      }
    },
    'Динамо Москва':{city:'Москва'},'МАХ':{city:'Москва'},'Торпедо':{city:'Нижний Новгород'},'Локомотив':{city:'Ярославль'},'Локомотив 2004':{city:'Ярославль'},'Крылья Советов':{city:'Москва'},'Сибирь':{city:'Новосибирск'},'Лада':{city:'Тольятти'},'Трактор':{city:'Челябинск'},'Ак Барс':{city:'Казань'},'Спартак':{city:'Москва'},'Динамо СПБ':{city:'Санкт-Петербург'},'СКА-Стрельна':{city:'Санкт-Петербург'},'АКМ':{city:'Новомосковск'},'ЦСКА':{city:'Москва'},'Армия СКА':{city:'Санкт-Петербург'},'Нефтехимик':{city:'Нижнекамск'},'Северсталь':{city:'Череповец'},'Красная Машина Юниор':{city:'Красногорск'}
  };
  const $=s=>document.querySelector(s);
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const done=m=>Number.isInteger(m.home_score)&&Number.isInteger(m.away_score)&&m.home_score!==m.away_score;
  async function get(path){const r=await fetch(API+path,{cache:'no-store'});if(!r.ok)throw Error(await r.text());return r.json()}
  function fmtDate(x){return new Date(x+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}
  function time(m){return String(m.start_time||'').slice(0,5)}
  function finish(m){return m.finish_type==='OT'?'ОТ':m.finish_type==='SO'?'буллиты':''}
  function pts(m,id,s){if(!done(m))return 0;const winner=(m.home_score>m.away_score?m.home_team_id:m.away_team_id)===id;return winner?s.win_points:(m.finish_type==='REG'?s.regulation_loss_points:s.ot_loss_points)}
  function row(team,group,data){const ms=data.matches.filter(m=>m.group_id===group.id&&[m.home_team_id,m.away_team_id].includes(team.id));let o={gp:0,w:0,rw:0,ow:0,l:0,rl:0,ol:0,gf:0,ga:0,gd:0,pts:0};for(const m of ms){if(!done(m))continue;o.gp++;const home=m.home_team_id===team.id;const f=home?m.home_score:m.away_score,a=home?m.away_score:m.home_score;o.gf+=f;o.ga+=a;o.pts+=pts(m,team.id,data.settings);if(f>a){o.w++;m.finish_type==='REG'?o.rw++:o.ow++}else{o.l++;m.finish_type==='REG'?o.rl++:o.ol++}}o.gd=o.gf-o.ga;return o}
  function groupRows(group,data){const teams=data.memberships.filter(x=>x.group_id===group.id).map(x=>data.teams.find(t=>t.id===x.team_id)).filter(Boolean);return teams.map(t=>({team:t,...row(t,group,data)})).sort((a,b)=>b.pts-a.pts||b.rw-a.rw||b.gd-a.gd||b.gf-a.gf||a.team.name.localeCompare(b.team.name,'ru')).map((x,i)=>({...x,place:i+1}))}
  function logo(name,cls=''){const src=TEAM_LOGOS[name];return src?`<img class="${cls}" src="${src}" alt="Логотип ${esc(name)}">`:''}
  function initials(name){return name.split(/\s+/).map(x=>x[0]).join('').slice(0,3).toUpperCase()}
  function socialIcon(type){
    if(type==='vk')return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3.6 7.2h3c.2 0 .4.1.5.4.6 1.7 1.5 3.1 2.4 4.1.5.5.8.7 1 .8.1 0 .2-.2.2-.5V7.7c0-.3.1-.5.4-.5h2.8c.3 0 .5.2.5.5v3.8c0 .3.1.5.2.5.2 0 .5-.2.9-.6 1-1.1 1.8-2.5 2.3-4 .1-.2.3-.3.5-.3h3c.5 0 .7.3.5.7-.5 1.5-1.8 3.4-3.5 5.2-.2.2-.2.5 0 .7 1.8 1.6 3 3.2 3.6 4.2.3.5.1.8-.4.8h-3.3c-.3 0-.5-.1-.7-.4-.8-1.1-1.6-2-2.4-2.6-.3-.2-.5-.1-.5.3v2.2c0 .3-.2.5-.5.5h-1.5c-4.3 0-7.2-2.9-8.7-10.8-.1-.5.1-.7.6-.7Z"/></svg>';
    if(type==='tg')return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21.4 4.1 18.3 19c-.2 1.1-.9 1.4-1.8.9l-4.7-3.5-2.3 2.2c-.3.3-.5.5-1 .5l.3-4.8 8.8-7.9c.4-.3-.1-.5-.6-.2L6.2 13l-4.7-1.5c-1-.3-1-1 .2-1.5L20 3c.9-.3 1.6.2 1.4 1.1Z"/></svg>';
    if(type==='max')return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5.2c0-.7.6-1.2 1.2-1.2h11.6c.7 0 1.2.6 1.2 1.2v10.6c0 .7-.6 1.2-1.2 1.2h-5l-3.5 3v-3H6.2c-.7 0-1.2-.6-1.2-1.2V5.2Zm3.1 3.2 2.6 5 1.3-2.5 1.3 2.5 2.6-5h-1.8l-.8 1.8-1.3-2.5-1.3 2.5-.8-1.8H8.1Z"/></svg>';
    return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm6.9 6h-3.1a15.8 15.8 0 0 0-1.4-3.3A8.1 8.1 0 0 1 18.9 8ZM12 4c.9 1.1 1.6 2.4 2 4h-4c.4-1.6 1.1-2.9 2-4ZM9.6 4.7A15.8 15.8 0 0 0 8.2 8H5.1a8.1 8.1 0 0 1 4.5-3.3ZM4 12c0-.7.1-1.4.3-2h3.5a16.7 16.7 0 0 0 0 4H4.3A8.4 8.4 0 0 1 4 12Zm1.1 4h3.1a15.8 15.8 0 0 0 1.4 3.3A8.1 8.1 0 0 1 5.1 16ZM12 20c-.9-1.1-1.6-2.4-2-4h4c-.4 1.6-1.1 2.9-2 4Zm2.4-.7a15.8 15.8 0 0 0 1.4-3.3h3.1a8.1 8.1 0 0 1-4.5 3.3ZM16.2 14a14.9 14.9 0 0 0 0-4h3.5a8.4 8.4 0 0 1 0 4h-3.5ZM14.3 10a13 13 0 0 1 0 4H9.7a13 13 0 0 1 0-4h4.6Z"/></svg>';
  }
  function renderSocials(meta){const labels={vk:'ВКонтакте',tg:'Telegram',max:'MAX',web:'Официальный сайт'},s=meta.socials||{};$('#socials').innerHTML=['vk','tg','max','web'].filter(k=>s[k]).map(k=>`<a class="social-link" href="${s[k]}" target="_blank" rel="noopener noreferrer" aria-label="${labels[k]}" title="${labels[k]}">${socialIcon(k)}</a>`).join('')}
  function renderNext(team,data,ms){const now=new Date();const upcoming=ms.filter(m=>!done(m)).sort((a,b)=>a.game_date.localeCompare(b.game_date)||time(a).localeCompare(time(b))||(a.game_no||0)-(b.game_no||0));const m=upcoming[0];if(!m){$('#nextMatch').innerHTML='<div class="empty">Следующих матчей в текущем туре нет.</div>';return}const home=data.teams.find(t=>t.id===m.home_team_id),away=data.teams.find(t=>t.id===m.away_team_id),place=[m.city,m.arena].filter(Boolean).join(' · ');$('#nextMatch').innerHTML=`<a class="next-match" href="/?match=${m.id}"><div class="next-team">${logo(home.name)}<span>${esc(home.name)}</span></div><div class="next-vs">—</div><div class="next-team away"><span>${esc(away.name)}</span>${logo(away.name)}</div><div class="next-meta"><strong>${fmtDate(m.game_date)} · ${time(m)||'—'}</strong><span>${esc(place||'Место уточняется')}<br>Матч №${m.game_no??'—'}</span></div></a>`}
  function renderMatches(team,data,ms){const sorted=[...ms].sort((a,b)=>a.game_date.localeCompare(b.game_date)||time(a).localeCompare(time(b))||(a.game_no||0)-(b.game_no||0));$('#matches').innerHTML=sorted.map(m=>{const home=data.teams.find(t=>t.id===m.home_team_id),away=data.teams.find(t=>t.id===m.away_team_id),g=data.groups.find(x=>x.id===m.group_id),place=[m.city,m.arena].filter(Boolean).join(' · ');return `<a class="match-row" href="/?match=${m.id}"><div class="match-info"><strong>${esc(g?.code||'')}</strong><br>${fmtDate(m.game_date)}${time(m)?'<br>'+time(m):''}</div><div class="match-team">${esc(home.name)}</div><div class="match-score"><strong>${done(m)?m.home_score+':'+m.away_score:'—'}</strong><span>${done(m)?finish(m):'предстоит'}</span></div><div class="match-team away">${esc(away.name)}</div><div class="match-place">${esc(place||'Место уточняется')}</div></a>`}).join('')||'<div class="empty">Матчи команды пока не добавлены.</div>'}
  function renderForm(team,ms){const finished=ms.filter(done).sort((a,b)=>b.game_date.localeCompare(a.game_date)||((b.game_no||0)-(a.game_no||0))).slice(0,5);$('#form').innerHTML=finished.reverse().map(m=>{const home=m.home_team_id===team.id,f=home?m.home_score:m.away_score,a=home?m.away_score:m.home_score,w=f>a;return `<span class="form-pill ${w?'win':'loss'}" title="${f}:${a}">${w?'В':'П'}</span>`}).join('')}
  async function init(){try{
    const id=Number(new URL(location.href).searchParams.get('team'));if(!id)throw Error('Команда не выбрана');
    const catalog=await get('/api/catalog'),tournament=catalog.tournaments?.[0];if(!tournament)throw Error('Турнир не найден');
    const stages=(catalog.stages||[]).filter(s=>Number(s.tournament_id)===Number(tournament.id)).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)),stage=stages[0];if(!stage)throw Error('Этап не найден');
    const data=await get('/api/data?tournament_slug='+encodeURIComponent(tournament.slug)+'&stage_id='+encodeURIComponent(stage.id)),team=data.teams.find(t=>Number(t.id)===id);if(!team)throw Error('Команда не найдена');
    const meta=TEAM_META[team.name]||{},membership=data.memberships.find(x=>x.team_id===team.id),group=data.groups.find(g=>g.id===membership?.group_id),rows=group?groupRows(group,data):[],teamRow=rows.find(r=>r.team.id===team.id)||{gp:0,w:0,l:0,gf:0,ga:0,gd:0,pts:0,place:'—'},allRows=data.groups.flatMap(g=>groupRows(g,data).map(r=>({...r,group_id:g.id}))).sort((a,b)=>b.pts-a.pts||b.rw-a.rw||b.gd-a.gd||b.gf-a.gf),overallPlace=allRows.findIndex(r=>r.team.id===team.id)+1;
    const ms=data.matches.filter(m=>[m.home_team_id,m.away_team_id].includes(team.id));
    document.title=team.name+' · Кубок России U16';$('#season').textContent=data.tournament.season||'2026/27';$('#teamKicker').textContent=(meta.city?meta.city+' · ':'')+(group?.name||group?.code||'Команда турнира');$('#teamName').textContent=team.name;$('#teamArena').textContent=meta.arena||((meta.city?meta.city+' · ':'')+'адрес арены будет добавлен');
    const src=TEAM_LOGOS[team.name];if(src){$('#teamLogo').src=src;$('#teamLogo').alt='Логотип '+team.name;$('#teamLogo').onerror=()=>{$('#teamLogo').style.display='none';$('#teamLogoFallback').style.display='grid';$('#teamLogoFallback').textContent=initials(team.name)}}else{$('#teamLogo').style.display='none';$('#teamLogoFallback').style.display='grid';$('#teamLogoFallback').textContent=initials(team.name)}
    renderSocials(meta);$('#groupName').textContent=group?.name||group?.code||'—';$('#groupPlace').textContent=teamRow.place||'—';
    $('#statsGrid').innerHTML=`<div class="stat-card"><strong>${overallPlace||'—'}</strong><span>место в общей таблице</span></div><div class="stat-card"><strong>${teamRow.gp}</strong><span>игр</span></div><div class="stat-card"><strong>${teamRow.w}</strong><span>побед</span></div><div class="stat-card"><strong>${teamRow.l}</strong><span>поражений</span></div><div class="stat-card"><strong>${teamRow.gf}:${teamRow.ga}</strong><span>шайбы</span></div><div class="stat-card"><strong>${teamRow.pts}</strong><span>очков</span></div>`;
    renderForm(team,ms);renderNext(team,data,ms);renderMatches(team,data,ms);
  }catch(e){console.error(e);$('#teamName').textContent='Команда не найдена';$('#teamArena').textContent='Вернитесь к списку команд и выберите нужную карточку.';$('#nextMatch').innerHTML='<div class="empty">Не удалось загрузить данные команды.</div>';$('#matches').innerHTML=''}}
  init();
})();